import { describe, it, beforeEach, afterEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonSandbox, type SinonStub } from "sinon";
import {
    migrateAutoGeneratedFlag,
    collectFlagBearingEffects,
    type MigratableEffect,
    type EffectHost,
    MIGRATION_FLAG_SCOPE,
    MIGRATION_FLAG_KEY,
} from "module/activeEffect/migrations/migrateAutoGeneratedFlag";
import { foundryApi } from "module/api/foundryApi";

function makeEffect(overrides: Partial<MigratableEffect> = {}): MigratableEffect {
    const base: MigratableEffect = {
        id: "eff1",
        type: "modifier",
        getFlag: () => false,
        update: sinon.stub().resolves(),
        ...overrides,
    };
    return base;
}

describe("migrateAutoGeneratedFlag", () => {
    let sandbox: SinonSandbox;
    let settingsGet: SinonStub;
    let settingsSet: SinonStub;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        settingsGet = sandbox.stub();
        settingsSet = sandbox.stub().resolves();
        sandbox.stub(foundryApi, "settings").value({
            get: settingsGet,
            set: settingsSet,
            register: sandbox.stub(),
        });
        sandbox.stub(foundryApi, "currentUser").value({ id: "gm1", isGM: true, active: true });
        sandbox.stub(foundryApi, "users").value([{ id: "gm1", isGM: true, active: true }]);
    });

    afterEach(() => {
        sandbox.restore();
    });

    it("collectFlagBearingEffects picks up only effects with the legacy flag set to true", () => {
        const flagBearing = makeEffect({ id: "e1", getFlag: () => true });
        const notFlagBearing = makeEffect({ id: "e2", getFlag: () => false });
        const host: EffectHost = { effects: [flagBearing, notFlagBearing] };
        expect(collectFlagBearingEffects([host])).to.deep.equal([flagBearing]);
    });

    it("flips type to autoGenerated and clears the flag for each flag-bearing effect", async () => {
        settingsGet.returns(false);
        const effect = makeEffect({ id: "e1", type: "modifier", getFlag: () => true });
        sandbox.stub(foundryApi, "collections").value({
            actors: [{ effects: [effect] }],
            items: [],
            packs: [],
        });

        await migrateAutoGeneratedFlag();

        expect((effect.update as SinonStub).calledOnce).to.be.true;
        const arg = (effect.update as SinonStub).firstCall.args[0];
        expect(arg).to.deep.equal({
            type: "autoGenerated",
            flags: { splittermond: { "-=autoGenerated": null } },
        });
        expect(settingsSet.calledOnceWith(MIGRATION_FLAG_SCOPE, MIGRATION_FLAG_KEY, true)).to.be.true;
    });

    it("is a no-op (but still sets done) when no flag-bearing effects exist", async () => {
        settingsGet.returns(false);
        const effect = makeEffect({ id: "e1", getFlag: () => false });
        sandbox.stub(foundryApi, "collections").value({
            actors: [{ effects: [effect] }],
            items: [],
            packs: [],
        });

        await migrateAutoGeneratedFlag();

        expect((effect.update as SinonStub).called).to.be.false;
        expect(settingsSet.calledOnceWith(MIGRATION_FLAG_SCOPE, MIGRATION_FLAG_KEY, true)).to.be.true;
    });

    it("does not run when the migration-done setting is already true", async () => {
        settingsGet.returns(true);
        const effect = makeEffect({ id: "e1", getFlag: () => true });
        sandbox.stub(foundryApi, "collections").value({
            actors: [{ effects: [effect] }],
            items: [],
            packs: [],
        });

        await migrateAutoGeneratedFlag();

        expect((effect.update as SinonStub).called).to.be.false;
        expect(settingsSet.called).to.be.false;
    });

    it("does not run when this user is not the first active GM", async () => {
        settingsGet.returns(false);
        sandbox.restore();
        sandbox = sinon.createSandbox();
        settingsGet = sandbox.stub().returns(false);
        settingsSet = sandbox.stub().resolves();
        sandbox.stub(foundryApi, "settings").value({ get: settingsGet, set: settingsSet, register: sandbox.stub() });
        sandbox.stub(foundryApi, "currentUser").value({ id: "gm2", isGM: true, active: true });
        sandbox.stub(foundryApi, "users").value([
            { id: "gm1", isGM: true, active: true },
            { id: "gm2", isGM: true, active: true },
        ]);
        const effect = makeEffect({ id: "e1", getFlag: () => true });
        sandbox.stub(foundryApi, "collections").value({
            actors: [{ effects: [effect] }],
            items: [],
            packs: [],
        });

        await migrateAutoGeneratedFlag();

        expect((effect.update as SinonStub).called).to.be.false;
        expect(settingsSet.called).to.be.false;
    });
});
