import { QuenchBatchContext } from "@ethaks/fvtt-quench";
import type SplittermondActor from "module/actor/actor";
import { migrateModifierToEffects } from "module/item/migrations/modifierToEffectMigration";
import { getAddModifier } from "module/item/item";
import type SplittermondItem from "module/item/item";
import { withActor } from "../fixtures";
import { passesEventually } from "../../util";

function armorData() {
    return {
        type: "armor",
        name: "Verrostete Rüstung",
        system: {
            modifier: "",
            equipped: true,
            defenseBonus: 2,
            tickMalus: 0,
            handicap: 1,
            damageReduction: 0,
            minStr: 2,
        },
    };
}

function equipmentData(modifier: string) {
    return {
        type: "equipment",
        name: "Amulett der Weisheit",
        system: { modifier },
    };
}

export function liveItemModifierFallbackTest(context: QuenchBatchContext) {
    const { describe, it, expect } = context;

    describe("live item modifier fallback", function () {
        this.timeout(15000);

        async function awaitAutoGeneratedEffects(item: FoundryDocument) {
            await passesEventually(
                () => {
                    expect(
                        item.effects.filter((e) => e.type === "autoGenerated").length,
                        "item rebuild did not create autoGenerated effects"
                    ).to.be.greaterThan(0);
                },
                1500,
                50
            );
        }

        async function waitForEffectFreeItem(item: FoundryDocument) {
            const ids = item.effects.filter((e) => e.type === "autoGenerated").map((e) => e.id);
            await item.deleteEmbeddedDocuments("ActiveEffect", ids);
            await passesEventually(
                () => {
                    expect(
                        item.effects.filter((e) => e.type === "autoGenerated").length,
                        "autoGenerated effects not yet deleted"
                    ).to.equal(0);
                },
                1500,
                50
            );
        }

        function modifierGroup(actor: SplittermondActor, groupId: string) {
            return actor.modifier.getForId(groupId).getModifiers();
        }

        it(
            "effect-free armor contributes live property modifiers evaluated against the real actor",
            withActor(async (actor) => {
                await actor.update({
                    system: { attributes: { strength: { initial: 1, advances: 0, species: 0 } } },
                });
                const [item] = await actor.createEmbeddedDocuments("Item", [armorData()]);
                await awaitAutoGeneratedEffects(item);
                await waitForEffectFreeItem(item);

                await actor.prepareData();

                const defense = modifierGroup(actor, "defense");
                expect(defense.length, "defense appears exactly once via the live path").to.equal(1);
                expect(await defense.sum(), "defenseBonus 2 arrives live").to.equal(2);
                expect(
                    await modifierGroup(actor, "handicap.armor").sum(),
                    "handicap 1 plus the minStr 2 deficit against strength 1"
                ).to.equal(2);
                expect(
                    await modifierGroup(actor, "tickmalus.armor").sum(),
                    "tick malus grows by the same deficit"
                ).to.equal(1);

                await actor.update({
                    system: { attributes: { strength: { initial: 4, advances: 0, species: 0 } } },
                });
                await actor.prepareData();

                expect(
                    await modifierGroup(actor, "handicap.armor").sum(),
                    "the malus re-binds to the live strength without a rebuild"
                ).to.equal(1);
                expect(await modifierGroup(actor, "defense").sum(), "defenseBonus is unaffected by strength").to.equal(
                    2
                );
            })
        );

        it(
            "updating an armor property switches from the live fallback to exactly one effect source",
            withActor(async (actor) => {
                const [item] = await actor.createEmbeddedDocuments("Item", [armorData()]);
                await awaitAutoGeneratedEffects(item);
                await waitForEffectFreeItem(item);
                await actor.prepareData();

                const live = modifierGroup(actor, "defense");
                expect(live.length, "pre-state: the live fallback provides defense exactly once").to.equal(1);
                expect(await live.sum()).to.equal(2);

                await item.update({ "system.defenseBonus": 3 });
                await awaitAutoGeneratedEffects(item);
                await actor.prepareData();

                expect(
                    item.effects.filter((e) => e.type === "autoGenerated").length,
                    "the update rebuilt autoGenerated effects"
                ).to.be.greaterThan(0);
                const afterTransition = modifierGroup(actor, "defense");
                expect(afterTransition.length, "no live/effect double counting after the transition").to.equal(1);
                expect(await afterTransition.sum(), "the effect source carries the new value").to.equal(3);
            })
        );

        it(
            "legacy string equipment keeps a single modifier source across the modifier-to-effect transport",
            withActor(async (actor) => {
                const [item] = await actor.createEmbeddedDocuments("Item", [equipmentData("defense +1")]);
                await awaitAutoGeneratedEffects(item);
                await waitForEffectFreeItem(item);

                await actor.prepareData();

                const live = modifierGroup(actor, "defense");
                expect(live.length, "the live string path registers defense exactly once").to.equal(1);
                expect(await live.sum(), "defense +1 arrives live").to.equal(1);

                await migrateModifierToEffects(item as unknown as SplittermondItem, getAddModifier());
                await passesEventually(
                    () => {
                        expect(item.system.modifier, "system.modifier not yet cleared").to.equal("");
                    },
                    1500,
                    50
                );

                await actor.prepareData();

                expect(
                    item.effects.filter((e) => e.type === "modifier").length,
                    "the transport created one modifier-type effect"
                ).to.equal(1);
                const afterTransport = modifierGroup(actor, "defense");
                expect(afterTransport.length, "still exactly one source after the transport").to.equal(1);
                expect(await afterTransport.sum(), "the transported value is unchanged").to.equal(1);
            })
        );
    });
}
