import { describe, it, beforeEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonSandbox, type SinonStub } from "sinon";
import { addModifierEffects, rebuildModifierEffects } from "module/activeEffect/effectBuilder";
import type { IModifier } from "module/modifiers";
import type { ICostModifier } from "module/util/costs/spellCostManagement";
import type { AddModifierResult, TaggedModifier, TaggedCostModifier } from "module/modifiers/modifierAddition";
import { of } from "module/modifiers/expressions/scalar";
import { of as costOf } from "module/modifiers/expressions/cost";
import { CostModifier } from "module/util/costs/Cost";

function makeScalarModifier(overrides: Partial<IModifier> = {}): IModifier {
    return {
        value: of(2),
        isBonus: true,
        groupId: "skills.acrobatics",
        selectable: false,
        attributes: { name: "Test Item", type: "innate" },
        effectType: "modifier",
        addTooltipFormulaElements() {},
        ...overrides,
    };
}

function makeCostModifier(overrides: Partial<ICostModifier> = {}): ICostModifier {
    return {
        label: "focus.reduction",
        value: costOf(CostModifier.zero),
        skill: null,
        attributes: {},
        effectType: "costModifier",
        ...overrides,
    };
}

function makeTagged(modifier: IModifier, rawFragment = "skills.acrobatics +2"): TaggedModifier {
    return { modifier, rawFragment };
}

function makeTaggedCost(modifier: ICostModifier, rawFragment = "focus.reduction 1"): TaggedCostModifier {
    return { modifier, rawFragment };
}

function makeAddModifierFn(result: AddModifierResult): SinonStub {
    return sinon.stub().returns(result);
}

function makeItem(effects: any[] = []) {
    return {
        uuid: "Item.test-uuid",
        system: { modifier: "skills.acrobatics +2" },
        effects,
        createEmbeddedDocuments: sinon.stub().resolves([]),
        deleteEmbeddedDocuments: sinon.stub().resolves([]),
    } as any;
}

describe("effectBuilder", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
    });

    afterEach(() => sandbox.restore());

    describe("addModifierEffects", () => {
        it("creates one effect per scalar modifier with correct type and name", async () => {
            const modifier = makeScalarModifier({ effectType: "modifier" });
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(modifier, "skills.acrobatics +2")],
                costModifiers: [],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "skills.acrobatics +2", "innate", 1);

            expect(addModifier.calledOnce).to.be.true;
            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects).to.have.length(1);
            expect(effects[0].type).to.equal("modifier");
            expect(effects[0].name).to.equal("skills.acrobatics +2");
            expect(effects[0].origin).to.equal("Item.test-uuid");
        });

        it("sets autoGenerated flag on created effects", async () => {
            const modifier = makeScalarModifier();
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(modifier)],
                costModifiers: [],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "skills.acrobatics +2", "innate", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects[0].flags.splittermond.autoGenerated).to.be.true;
        });

        it("creates effects for cost modifiers with type costModifier", async () => {
            const modifier = makeCostModifier();
            const addModifier = makeAddModifierFn({
                modifiers: [],
                costModifiers: [makeTaggedCost(modifier, "focus.reduction 1")],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "focus.reduction 1", "magic", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects).to.have.length(1);
            expect(effects[0].type).to.equal("costModifier");
            expect(effects[0].name).to.equal("focus.reduction 1");
        });

        it("creates effects for all modifier kinds with correct EffectType", async () => {
            const inverse = makeScalarModifier({ effectType: "inverseModifier" });
            const multi = makeScalarModifier({ effectType: "multiplicativeModifier" });
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(inverse, "fragment1"), makeTagged(multi, "fragment2")],
                costModifiers: [],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "fragment1, fragment2", "innate", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects[0].type).to.equal("inverseModifier");
            expect(effects[1].type).to.equal("multiplicativeModifier");
        });

        it("does not call createEmbeddedDocuments when addModifier returns no results", async () => {
            const addModifier = makeAddModifierFn({ modifiers: [], costModifiers: [] });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "some.path +1", "innate", 1);

            expect(item.createEmbeddedDocuments.called).to.be.false;
        });

        it("does not call addModifier for an empty modifier string", async () => {
            const addModifier = makeAddModifierFn({ modifiers: [], costModifiers: [] });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "   ", "innate", 1);

            expect(addModifier.called).to.be.false;
            expect(item.createEmbeddedDocuments.called).to.be.false;
        });

        it("creates multiple effects when one fragment fan-outs to N modifiers", async () => {
            const m1 = makeScalarModifier({ groupId: "skill.id1" });
            const m2 = makeScalarModifier({ groupId: "skill.id2" });
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(m1, "npcattacks +2"), makeTagged(m2, "npcattacks +2")],
                costModifiers: [],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "npcattacks +2", "innate", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects).to.have.length(2);
        });

        it("stores rawInput in effect flags", async () => {
            const modifier = makeScalarModifier();
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(modifier, "skills.acrobatics +2")],
                costModifiers: [],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "skills.acrobatics +2", "innate", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects[0].flags.splittermond.rawInput).to.equal("skills.acrobatics +2");
        });
    });

    describe("rebuildModifierEffects", () => {
        it("deletes existing autoGenerated effects before creating new ones", async () => {
            const existingEffect = {
                id: "old-id",
                getFlag: sinon.stub().withArgs("splittermond", "autoGenerated").returns(true),
            };
            const modifier = makeScalarModifier();
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(modifier)],
                costModifiers: [],
            });
            const item = makeItem([existingEffect]);

            await rebuildModifierEffects(addModifier, item, "magic", 1);

            expect(item.deleteEmbeddedDocuments.calledWith("ActiveEffect", ["old-id"])).to.be.true;
            expect(item.createEmbeddedDocuments.calledOnce).to.be.true;
        });

        it("does not create effects when modifier string is empty", async () => {
            const addModifier = makeAddModifierFn({ modifiers: [], costModifiers: [] });
            const item = makeItem();
            item.system.modifier = "";

            await rebuildModifierEffects(addModifier, item, "magic", 1);

            expect(item.createEmbeddedDocuments.called).to.be.false;
        });

        it("passes transfer=true and disabled=false on all effects", async () => {
            const modifier = makeScalarModifier();
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(modifier)],
                costModifiers: [],
            });
            const item = makeItem();

            await rebuildModifierEffects(addModifier, item, "innate", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects[0].transfer).to.be.true;
            expect(effects[0].disabled).to.be.false;
        });

        it("only deletes auto-generated effects, leaving manual effects untouched", async () => {
            const autoEffect = {
                id: "auto-id",
                getFlag: sinon.stub().withArgs("splittermond", "autoGenerated").returns(true),
            };
            const manualEffect = {
                id: "manual-id",
                getFlag: sinon.stub().withArgs("splittermond", "autoGenerated").returns(false),
            };
            const addModifier = makeAddModifierFn({ modifiers: [], costModifiers: [] });
            const item = makeItem([autoEffect, manualEffect]);
            item.system.modifier = "";

            await rebuildModifierEffects(addModifier, item, "magic", 1);

            expect(item.deleteEmbeddedDocuments.calledWith("ActiveEffect", ["auto-id"])).to.be.true;
            const deletedIds: string[] = item.deleteEmbeddedDocuments.firstCall.args[1];
            expect(deletedIds).to.not.include("manual-id");
        });

        it("does not call deleteEmbeddedDocuments when there are no auto-generated effects", async () => {
            const addModifier = makeAddModifierFn({ modifiers: [], costModifiers: [] });
            const item = makeItem();
            item.system.modifier = "";

            await rebuildModifierEffects(addModifier, item, "magic", 1);

            expect(item.deleteEmbeddedDocuments.called).to.be.false;
        });
    });

    describe("addModifierEffects — mixed scalar and cost", () => {
        it("produces scalar effects before cost effects in the combined array", async () => {
            const scalar = makeScalarModifier();
            const cost = makeCostModifier();
            const addModifier = makeAddModifierFn({
                modifiers: [makeTagged(scalar, "skills.acrobatics +2")],
                costModifiers: [makeTaggedCost(cost, "focus.reduction 1")],
            });
            const item = makeItem();

            await addModifierEffects(addModifier, item, "skills.acrobatics +2, focus.reduction 1", "magic", 1);

            const [, effects] = item.createEmbeddedDocuments.firstCall.args;
            expect(effects).to.have.length(2);
            expect(effects[0].type).to.equal("modifier");
            expect(effects[1].type).to.equal("costModifier");
        });
    });
});
