import { describe, it } from "mocha";
import { expect } from "chai";
import { buildEffectCardContext } from "module/activeEffect/effectCardContext";
import type { EffectCardEffect } from "module/activeEffect/effectCardContext";
import type { EffectType } from "module/activeEffect/dataModel/effectTypes";

function makeEffect(overrides: Partial<EffectCardEffect> = {}): EffectCardEffect {
    return {
        isSuppressed: false,
        disabled: false,
        autoGenerated: false,
        type: "modifier",
        durationMode: "permanent",
        duration: {
            expired: false,
            value: null,
            units: "",
        },
        ...overrides,
    };
}

describe("buildEffectCardContext", () => {
    describe("badges", () => {
        it("suppressed effect includes the suppressed badge", () => {
            const result = buildEffectCardContext(makeEffect({ isSuppressed: true }));

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-link-slash");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.suppressed");
            expect(result.badges[0].cssClass).to.equal("badge-suppressed");
        });

        it("expired effect includes the expired badge", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: true,
                        value: 3,
                        units: "rounds",
                        start: { round: 5 },
                    },
                })
            );

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-hourglass-end");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.expired");
            expect(result.badges[0].cssClass).to.equal("badge-expired");
        });

        it("channelled durationMode includes the channelled badge", () => {
            const result = buildEffectCardContext(makeEffect({ durationMode: "channelled" }));

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-arrows-to-circle");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.channelled");
            expect(result.badges[0].cssClass).to.equal("badge-channelled");
        });

        it("autoGenerated effect includes the generated-from-item-property badge", () => {
            const result = buildEffectCardContext(makeEffect({ autoGenerated: true }));

            const generatedBadge = result.badges.find((b) => b.cssClass === "badge-generated");
            expect(generatedBadge).to.exist;
            expect(generatedBadge?.icon).to.equal("fa-wand-magic-sparkles");
            expect(generatedBadge?.tooltipKey).to.equal("splittermond.activeEffect.badge.generatedFromItemProperty");
        });

        it("non-generated effect does not include the generated badge", () => {
            const result = buildEffectCardContext(makeEffect({ autoGenerated: false }));

            expect(result.badges.find((b) => b.cssClass === "badge-generated")).to.be.undefined;
        });

        it("timed effect does not add a timed badge (ticks are shown via showTicks)", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: false,
                        value: 3,
                        units: "rounds",
                        start: { round: 5 },
                    },
                })
            );

            expect(result.badges.find((b) => b.cssClass === "badge-timed")).to.be.undefined;
            expect(result.showTicks).to.be.true;
        });

        it("expired timed effect does not include the timed badge", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: true,
                        value: 3,
                        units: "rounds",
                        start: { round: 5 },
                    },
                })
            );

            expect(result.badges.find((b) => b.cssClass === "badge-timed")).to.be.undefined;
            expect(result.badges.find((b) => b.cssClass === "badge-expired")).to.exist;
        });

        it("disabled effect still computes badges (disabled is orthogonal)", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    disabled: true,
                    isSuppressed: true,
                })
            );

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].cssClass).to.equal("badge-suppressed");
        });
    });

    describe("timeToExpirationDisplay and showTicks", () => {
        it("channelled effect has null display and showTicks false", () => {
            const result = buildEffectCardContext(makeEffect({ durationMode: "channelled" }));

            expect(result.timeToExpirationDisplay).to.be.null;
            expect(result.showTicks).to.be.false;
        });

        it("timed effect with a label surfaces it as the display", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: false,
                        value: 5,
                        units: "rounds",
                        label: "3",
                        start: { round: 10 },
                    },
                })
            );

            expect(result.timeToExpirationDisplay).to.equal("3");
            expect(result.showTicks).to.be.true;
        });

        it("timed effect without a label has null display", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: false,
                        value: 5,
                        units: "rounds",
                        start: { round: 10 },
                    },
                })
            );

            expect(result.timeToExpirationDisplay).to.be.null;
            expect(result.showTicks).to.be.true;
        });

        it("expired timed effect surfaces the label but showTicks is false", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: true,
                        value: 5,
                        units: "rounds",
                        label: "0",
                        start: { round: 10 },
                    },
                })
            );

            expect(result.timeToExpirationDisplay).to.equal("0");
            expect(result.showTicks).to.be.false;
        });

        it("permanent effect has null display and showTicks false", () => {
            const result = buildEffectCardContext(makeEffect({ durationMode: "permanent" }));

            expect(result.timeToExpirationDisplay).to.be.null;
            expect(result.showTicks).to.be.false;
        });
    });

    describe("typeCssClass", () => {
        const highlightedPairs: Array<{
            rawType: EffectType;
            expectedClass: string;
        }> = [
            { rawType: "spellEffect", expectedClass: "effect-type-spellEffect" },
            {
                rawType: "attackEffect",
                expectedClass: "effect-type-attackEffect",
            },
            {
                rawType: "spellEnhancedEffect",
                expectedClass: "effect-type-spellEnhancedEffect",
            },
            { rawType: "modifier", expectedClass: "" },
        ];

        highlightedPairs.forEach(({ rawType, expectedClass }) => {
            it(`type "${rawType}" produces typeCssClass "${expectedClass}"`, () => {
                const result = buildEffectCardContext(makeEffect({ type: rawType }));

                expect(result.typeCssClass).to.equal(expectedClass);
            });
        });

        it('type "base" produces typeCssClass ""', () => {
            const result = buildEffectCardContext(makeEffect({ type: "base" }));

            expect(result.typeCssClass).to.equal("");
        });
    });
});
