import { describe, it } from "mocha";
import { expect } from "chai";
import { buildEffectCardContext, showInDefaultView } from "module/activeEffect/effectCardContext";
import type { DefaultViewEffect, EffectCardEffect } from "module/activeEffect/effectCardContext";
import type { EffectType } from "module/activeEffect/dataModel/effectTypes";

function makeEffect(overrides: Partial<EffectCardEffect> = {}): EffectCardEffect {
    return {
        isSuppressed: false,
        type: "modifier",
        durationMode: "permanent",
        duration: {
            expired: false,
            value: null,
            units: "",
        },
        ...overrides,
    };
}

describe("buildEffectCardContext", () => {
    describe("badges", () => {
        it("suppressed effect includes the suppressed badge", () => {
            const result = buildEffectCardContext(makeEffect({ isSuppressed: true }));

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-link-slash");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.suppressed");
            expect(result.badges[0].cssClass).to.equal("badge-suppressed");
        });

        it("expired effect includes the expired badge", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: true,
                        value: 3,
                        units: "rounds",
                        start: { round: 5 },
                    },
                })
            );

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-hourglass-end");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.expired");
            expect(result.badges[0].cssClass).to.equal("badge-expired");
        });

        it("channelled durationMode includes the channelled badge", () => {
            const result = buildEffectCardContext(makeEffect({ durationMode: "channelled" }));

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-arrows-to-circle");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.channelled");
            expect(result.badges[0].cssClass).to.equal("badge-channelled");
        });

        it("autoGenerated effect includes the generated-from-item-property badge", () => {
            const result = buildEffectCardContext(makeEffect({ type: "autoGenerated" }));

            const generatedBadge = result.badges.find((b) => b.cssClass === "badge-generated");
            expect(generatedBadge).to.exist;
            expect(generatedBadge?.icon).to.equal("fa-wand-magic-sparkles");
            expect(generatedBadge?.tooltipKey).to.equal("splittermond.activeEffect.badge.generatedFromItemProperty");
        });

        it("non-generated effect does not include the generated badge", () => {
            const result = buildEffectCardContext(makeEffect({ type: "modifier" }));

            expect(result.badges.find((b) => b.cssClass === "badge-generated")).to.be.undefined;
        });

        it("type 'base' produces no generated badge (strict ===, not truthy fallback)", () => {
            const result = buildEffectCardContext(makeEffect({ type: "base" }));

            expect(result.badges.find((b) => b.cssClass === "badge-generated")).to.be.undefined;
        });

        it("timed effect does not add a timed badge (ticks are shown via showTicks)", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: false,
                        value: 3,
                        units: "rounds",
                        start: { round: 5 },
                    },
                })
            );

            expect(result.badges.find((b) => b.cssClass === "badge-timed")).to.be.undefined;
            expect(result.showTicks).to.be.true;
        });

        it("expired timed effect does not include the timed badge", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: true,
                        value: 3,
                        units: "rounds",
                        start: { round: 5 },
                    },
                })
            );

            expect(result.badges.find((b) => b.cssClass === "badge-timed")).to.be.undefined;
            expect(result.badges.find((b) => b.cssClass === "badge-expired")).to.exist;
        });

        it("ineffective effect includes the bonus exhausted badge", () => {
            const result = buildEffectCardContext(makeEffect({ isIneffective: true }));

            expect(result.badges).to.have.length(1);
            expect(result.badges[0].icon).to.equal("fa-droplet-slash");
            expect(result.badges[0].tooltipKey).to.equal("splittermond.activeEffect.badge.bonusExhausted");
            expect(result.badges[0].cssClass).to.equal("badge-bonus-exhausted");
        });

        it("effective effect does not include the bonus exhausted badge", () => {
            const result = buildEffectCardContext(makeEffect({ isIneffective: false }));

            expect(result.badges.find((b) => b.cssClass === "badge-bonus-exhausted")).to.be.undefined;
        });

        it("effect without exhaustion state has no bonus exhausted badge", () => {
            const result = buildEffectCardContext(makeEffect());

            expect(result.badges.find((b) => b.cssClass === "badge-bonus-exhausted")).to.be.undefined;
        });
    });

    describe("timeToExpirationDisplay and showTicks", () => {
        it("channelled effect has null display and showTicks false", () => {
            const result = buildEffectCardContext(makeEffect({ durationMode: "channelled" }));

            expect(result.timeToExpirationDisplay).to.be.null;
            expect(result.showTicks).to.be.false;
        });

        it("timed effect with a label surfaces it as the display", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: false,
                        value: 5,
                        units: "rounds",
                        label: "3",
                        start: { round: 10 },
                    },
                })
            );

            expect(result.timeToExpirationDisplay).to.equal("3");
            expect(result.showTicks).to.be.true;
        });

        it("timed effect without a label has null display", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: false,
                        value: 5,
                        units: "rounds",
                        start: { round: 10 },
                    },
                })
            );

            expect(result.timeToExpirationDisplay).to.be.null;
            expect(result.showTicks).to.be.true;
        });

        it("expired timed effect surfaces the label but showTicks is false", () => {
            const result = buildEffectCardContext(
                makeEffect({
                    durationMode: "timed",
                    duration: {
                        expired: true,
                        value: 5,
                        units: "rounds",
                        label: "0",
                        start: { round: 10 },
                    },
                })
            );

            expect(result.timeToExpirationDisplay).to.equal("0");
            expect(result.showTicks).to.be.false;
        });

        it("permanent effect has null display and showTicks false", () => {
            const result = buildEffectCardContext(makeEffect({ durationMode: "permanent" }));

            expect(result.timeToExpirationDisplay).to.be.null;
            expect(result.showTicks).to.be.false;
        });
    });

    describe("typeCssClass", () => {
        const highlightedPairs: Array<{
            rawType: EffectType;
            expectedClass: string;
        }> = [
            { rawType: "spellEffect", expectedClass: "effect-type-spellEffect" },
            {
                rawType: "attackEffect",
                expectedClass: "effect-type-attackEffect",
            },
            {
                rawType: "spellEnhancedEffect",
                expectedClass: "effect-type-spellEnhancedEffect",
            },
            { rawType: "modifier", expectedClass: "" },
        ];

        highlightedPairs.forEach(({ rawType, expectedClass }) => {
            it(`type "${rawType}" produces typeCssClass "${expectedClass}"`, () => {
                const result = buildEffectCardContext(makeEffect({ type: rawType }));

                expect(result.typeCssClass).to.equal(expectedClass);
            });
        });

        it('type "base" produces typeCssClass ""', () => {
            const result = buildEffectCardContext(makeEffect({ type: "base" }));

            expect(result.typeCssClass).to.equal("");
        });
    });
});

function makeDefaultViewEffect(overrides: Partial<DefaultViewEffect> = {}): DefaultViewEffect {
    return {
        fromItem: true,
        autoGenerated: true,
        sourceItemType: "weapon",
        durationMode: "permanent",
        ...overrides,
    };
}

describe("showInDefaultView", () => {
    describe("actor-owned effects", () => {
        const fromItemCombinations: Array<Omit<DefaultViewEffect, "fromItem">> = [
            { autoGenerated: true, sourceItemType: "weapon", durationMode: "permanent" },
            { autoGenerated: false, sourceItemType: "weapon", durationMode: "permanent" },
            { autoGenerated: true, sourceItemType: "mastery", durationMode: "permanent" },
            { autoGenerated: false, sourceItemType: "mastery", durationMode: "permanent" },
            { autoGenerated: true, sourceItemType: "statuseffect", durationMode: "permanent" },
            { autoGenerated: false, sourceItemType: "statuseffect", durationMode: "permanent" },
            { autoGenerated: true, sourceItemType: null, durationMode: "permanent" },
            { autoGenerated: false, sourceItemType: null, durationMode: "permanent" },
        ];

        fromItemCombinations.forEach((combination) => {
            it(`fromItem: false wins over every other predicate (${JSON.stringify(combination)})`, () => {
                const result = showInDefaultView({ ...combination, fromItem: false });

                expect(result).to.be.true;
            });
        });
    });

    describe("non-permanent durations", () => {
        it("shows timed effects regardless of expiry — the predicate keys off durationMode alone", () => {
            const result = showInDefaultView(makeDefaultViewEffect({ durationMode: "timed" }));

            expect(result).to.be.true;
        });

        it("shows channelled effects", () => {
            const result = showInDefaultView(makeDefaultViewEffect({ durationMode: "channelled" }));

            expect(result).to.be.true;
        });

        it("shows timed auto-generated effects from a non-statuseffect item", () => {
            const result = showInDefaultView(
                makeDefaultViewEffect({ durationMode: "timed", autoGenerated: true, sourceItemType: "weapon" })
            );

            expect(result).to.be.true;
        });

        it("shows channelled auto-generated effects from a non-statuseffect item", () => {
            const result = showInDefaultView(
                makeDefaultViewEffect({ durationMode: "channelled", autoGenerated: true, sourceItemType: "weapon" })
            );

            expect(result).to.be.true;
        });
    });

    describe("permanent item-based effects", () => {
        it("shows a manual effect from a statuseffect item", () => {
            const result = showInDefaultView(
                makeDefaultViewEffect({ sourceItemType: "statuseffect", autoGenerated: false })
            );

            expect(result).to.be.true;
        });

        it("hides an auto-generated effect from a statuseffect item", () => {
            const result = showInDefaultView(
                makeDefaultViewEffect({ sourceItemType: "statuseffect", autoGenerated: true })
            );

            expect(result).to.be.false;
        });

        [true, false].forEach((autoGenerated) => {
            ["weapon", "mastery"].forEach((sourceItemType) => {
                it(`hides a permanent effect from a "${sourceItemType}" item (autoGenerated: ${autoGenerated})`, () => {
                    const result = showInDefaultView(
                        makeDefaultViewEffect({
                            autoGenerated,
                            sourceItemType,
                        })
                    );

                    expect(result).to.be.false;
                });
            });
        });

        it("hides a permanent effect whose origin item is unresolvable", () => {
            const result = showInDefaultView(makeDefaultViewEffect({ sourceItemType: null }));

            expect(result).to.be.false;
        });
    });
});
