import { describe, it, beforeEach, afterEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonSandbox } from "sinon";
import { buildPropertyDerivedEffectData } from "module/activeEffect/propertyEffectBuilder";
import { foundryApi } from "module/api/foundryApi";
import { serialize, deserialize } from "module/modifiers/expressions/scalar/serialization";
import { evaluate, of } from "module/modifiers/expressions/scalar";
import type SplittermondItem from "module/item/item";

interface MockModifierEntry {
    path: string;
    serializedValue: unknown;
    implementation: string;
    selectable: boolean;
    attributes: { name: string; type: string };
}

interface MockEffect {
    name: string;
    origin: string;
    type: string;
    transfer: boolean;
    disabled: boolean;
    system: { modifiers: MockModifierEntry[]; costModifiers: unknown[] };
    flags: Record<string, unknown>;
}

function makeItem(type: string, system: object, name = "Test Item"): SplittermondItem {
    return { type, name, uuid: "Item.test-uuid", system } as unknown as SplittermondItem;
}

function asEffects(result: unknown): MockEffect[] {
    return result as MockEffect[];
}

function pathsOf(effects: MockEffect[]): string[] {
    return effects.flatMap((e) => e.system.modifiers.map((m) => m.path));
}

function findEffectByPath(effects: MockEffect[], path: string): MockEffect {
    const effect = effects.find((e) => e.system.modifiers.some((m) => m.path === path));
    if (!effect) throw new Error(`no effect for path ${path}`);
    return effect;
}

function entryOf(effect: MockEffect, path: string): MockModifierEntry {
    const entry = effect.system.modifiers.find((m) => m.path === path);
    if (!entry) throw new Error(`no entry for path ${path} on effect ${effect.name}`);
    return entry;
}

function hasReference(serialized: unknown): boolean {
    if (!serialized || typeof serialized !== "object") return false;
    const s = serialized as { type: string; args?: unknown[]; left?: unknown; right?: unknown; arg?: unknown };
    if (s.type === "reference") return true;
    if (s.type === "max" || s.type === "min") return (s.args as unknown[]).some(hasReference);
    if (s.type === "add" || s.type === "subtract" || s.type === "multiply" || s.type === "divide")
        return hasReference(s.left) || hasReference(s.right);
    if (s.type === "abs") return hasReference(s.arg);
    return false;
}

describe("buildPropertyDerivedEffectData", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        const shortForms: Record<string, string> = {
            charisma: "AUS",
            agility: "BEW",
            intuition: "INT",
            constitution: "KON",
            mystic: "MYS",
            strength: "STÄ",
            mind: "VER",
            willpower: "WIL",
        };
        const labelKeys: Record<string, string> = {
            defense: "Verteidigung",
            damagereduction: "Schadensreduktion",
            handicapArmor: "Behinderung (Rüstung)",
            tickmalusArmor: "Tickmalus (Rüstung)",
            handicapShield: "Behinderung (Schild)",
            tickmalusShield: "Tickmalus (Schild)",
            defenseWeaponMalus: "Verteidigung (Waffenmalus)",
        };
        sandbox.stub(foundryApi, "localize").callsFake((key: string) => {
            const attr = key.match(/^splittermond\.attribute\.([^.]+)\.(short|long)$/);
            if (attr) return attr[2] === "short" ? (shortForms[attr[1]] ?? attr[1]) : attr[1];
            const label = key.match(/^splittermond\.activeEffect\.propertyEffectName\.([^.]+)$/);
            if (label) return labelKeys[label[1]] ?? label[1];
            return key;
        });
    });

    afterEach(() => {
        sandbox.restore();
    });

    describe("armor", () => {
        it("emits one effect per entry: defense, damagereduction, handicap.armor, tickmalus.armor", () => {
            const item = makeItem("armor", {
                defenseBonus: 2,
                damageReduction: 3,
                handicap: 1,
                tickMalus: 4,
                minStr: 13,
            });
            const effects = asEffects(buildPropertyDerivedEffectData(item));

            expect(effects).to.have.length(4);
            expect(pathsOf(effects)).to.have.members([
                "defense",
                "damagereduction",
                "handicap.armor",
                "tickmalus.armor",
            ]);
            for (const effect of effects) {
                expect(effect.type).to.equal("autoGenerated");
                expect(effect.transfer).to.equal(true);
                expect(effect.disabled).to.equal(false);
                expect(effect.origin).to.equal("Item.test-uuid");
                expect(effect.flags).to.deep.equal({});
                expect(effect.system.modifiers).to.have.length(1);
                expect(effect.system.costModifiers).to.deep.equal([]);
            }
        });

        it("names each effect with the localized property label and item name", () => {
            const item = makeItem("armor", {
                defenseBonus: 2,
                damageReduction: 3,
                handicap: 1,
                tickMalus: 4,
                minStr: 13,
            });
            const effects = asEffects(buildPropertyDerivedEffectData(item));

            const names = effects.map((e) => e.name).sort();
            expect(names).to.deep.equal(
                [
                    "Behinderung (Rüstung): Test Item",
                    "Schadensreduktion: Test Item",
                    "Tickmalus (Rüstung): Test Item",
                    "Verteidigung: Test Item",
                ].sort()
            );
        });

        it("returns [] when every property-derived field is zero/null", () => {
            const item = makeItem("armor", {
                defenseBonus: 0,
                damageReduction: null,
                handicap: 0,
                tickMalus: 0,
                minStr: null,
            });
            expect(buildPropertyDerivedEffectData(item)).to.deep.equal([]);
        });

        it("omits the strength reference when minStr is null", () => {
            const item = makeItem("armor", {
                defenseBonus: 0,
                handicap: 2,
                tickMalus: 0,
                damageReduction: 0,
                minStr: null,
            });
            const effects = asEffects(buildPropertyDerivedEffectData(item));
            const handicapEffect = findEffectByPath(effects, "handicap.armor");
            expect(hasReference(entryOf(handicapEffect, "handicap.armor").serializedValue)).to.be.false;
        });

        it("attributeMalus stays live-reactive to strength after round-trip", async () => {
            const item = makeItem("armor", {
                defenseBonus: 0,
                handicap: 0,
                tickMalus: 0,
                damageReduction: 0,
                minStr: 13,
            });
            const effects = asEffects(buildPropertyDerivedEffectData(item));
            const handicapEffect = findEffectByPath(effects, "handicap.armor");
            const serialized = entryOf(handicapEffect, "handicap.armor").serializedValue;
            const deserialized = deserialize(
                serialized as Parameters<typeof deserialize>[0],
                () => ({ attributes: { strength: { value: 10 } } }) as never
            );
            expect(await evaluate(deserialized)).to.equal(3);
        });
    });

    describe("shield", () => {
        it("emits handicap.shield / tickmalus.shield with references per parsed minAttributes entry", () => {
            const item = makeItem("shield", {
                defenseBonus: 1,
                handicap: 1,
                tickMalus: 2,
                minAttributes: "BEW 13, AUS 12",
            });
            const effects = asEffects(buildPropertyDerivedEffectData(item));
            expect(pathsOf(effects)).to.have.members(["defense", "handicap.shield", "tickmalus.shield"]);
            const handicapEffect = findEffectByPath(effects, "handicap.shield");
            expect(hasReference(entryOf(handicapEffect, "handicap.shield").serializedValue)).to.be.true;
        });

        it("with empty minAttributes has no reference (just of(handicap))", () => {
            const item = makeItem("shield", { defenseBonus: 1, handicap: 1, tickMalus: 0, minAttributes: "" });
            const effects = asEffects(buildPropertyDerivedEffectData(item));
            const handicapEffect = findEffectByPath(effects, "handicap.shield");
            expect(hasReference(entryOf(handicapEffect, "handicap.shield").serializedValue)).to.be.false;
        });
    });

    describe("weapon", () => {
        it("emits a defense malus of 2 when the Unhandlich feature is present", () => {
            const item = makeItem("weapon", { features: { hasFeature: (f: string) => f === "Unhandlich" } });
            const effects = asEffects(buildPropertyDerivedEffectData(item));
            expect(effects).to.have.length(1);
            expect(pathsOf(effects)).to.deep.equal(["defense"]);
            const defenseEffect = findEffectByPath(effects, "defense");
            expect(entryOf(defenseEffect, "defense").serializedValue).to.deep.equal(serialize(of(-2)));
        });

        it("names the weapon defense malus with defenseWeaponMalus key, not the defense key", () => {
            const item = makeItem("weapon", { features: { hasFeature: (f: string) => f === "Unhandlich" } });
            const effects = asEffects(buildPropertyDerivedEffectData(item));
            expect(effects[0].name).to.equal("Verteidigung (Waffenmalus): Test Item");
        });

        it("returns [] when Unhandlich is absent", () => {
            const item = makeItem("weapon", { features: { hasFeature: () => false } });
            expect(buildPropertyDerivedEffectData(item)).to.deep.equal([]);
        });
    });

    describe("non-property item types", () => {
        it("returns [] for equipment", () => {
            const item = makeItem("equipment", { modifier: "skills.acrobatics +2" });
            expect(buildPropertyDerivedEffectData(item)).to.deep.equal([]);
        });
    });
});
