import { describe, it, beforeEach, afterEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonSandbox } from "sinon";
import { buildPropertyDerivedEffectData } from "module/activeEffect/propertyEffectBuilder";
import { foundryApi } from "module/api/foundryApi";
import { serialize, deserialize } from "module/modifiers/expressions/scalar/serialization";
import { evaluate, of } from "module/modifiers/expressions/scalar";

function makeItem(type: string, system: object, name = "Test Item"): any {
    return {
        type,
        name,
        uuid: "Item.test-uuid",
        system,
    };
}

function modifierPaths(effect: any): string[] {
    return (effect.system.modifiers as Array<{ path: string }>).map((m) => m.path);
}

function findEntry(effect: any, path: string): { path: string; serializedValue: any } {
    const entry = (effect.system.modifiers as Array<{ path: string; serializedValue: unknown }>).find(
        (m) => m.path === path
    );
    if (!entry) throw new Error(`no entry for path ${path}`);
    return entry as { path: string; serializedValue: any };
}

function hasReference(serialized: unknown): boolean {
    if (!serialized || typeof serialized !== "object") return false;
    const s = serialized as { type: string; args?: unknown[]; left?: unknown; right?: unknown; arg?: unknown };
    if (s.type === "reference") return true;
    if (s.type === "max" || s.type === "min") return (s.args as unknown[]).some(hasReference);
    if (s.type === "add" || s.type === "subtract" || s.type === "multiply" || s.type === "divide")
        return hasReference(s.left) || hasReference(s.right);
    if (s.type === "abs") return hasReference(s.arg);
    return false;
}

describe("buildPropertyDerivedEffectData", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        const shortForms: Record<string, string> = {
            charisma: "AUS",
            agility: "BEW",
            intuition: "INT",
            constitution: "KON",
            mystic: "MYS",
            strength: "STÄ",
            mind: "VER",
            willpower: "WIL",
        };
        sandbox.stub(foundryApi, "localize").callsFake((key: string) => {
            const m = key.match(/^splittermond\.attribute\.([^.]+)\.(short|long)$/);
            if (m) return m[2] === "short" ? (shortForms[m[1]] ?? m[1]) : m[1];
            return key;
        });
    });

    afterEach(() => {
        sandbox.restore();
    });

    describe("armor", () => {
        it("emits defense, damagereduction, handicap.armor, tickmalus.armor with a strength reference", () => {
            const item = makeItem("armor", {
                defenseBonus: 2,
                damageReduction: 3,
                handicap: 1,
                tickMalus: 4,
                minStr: 13,
            });
            const effect = buildPropertyDerivedEffectData(item);

            expect(effect).to.not.be.null;
            expect(effect!.type).to.equal("autoGenerated");
            expect(effect!.transfer).to.equal(true);
            expect(effect!.disabled).to.equal(false);
            expect(effect!.name).to.equal("Ausrüstung: Test Item");
            expect(effect!.origin).to.equal("Item.test-uuid");
            expect(modifierPaths(effect)).to.have.members([
                "defense",
                "damagereduction",
                "handicap.armor",
                "tickmalus.armor",
            ]);
            expect(hasReference(findEntry(effect, "handicap.armor").serializedValue)).to.be.true;
            expect(hasReference(findEntry(effect, "tickmalus.armor").serializedValue)).to.be.true;
            expect(hasReference(findEntry(effect, "defense").serializedValue)).to.be.false;
        });

        it("returns null when every property-derived field is zero/null", () => {
            const item = makeItem("armor", {
                defenseBonus: 0,
                damageReduction: null,
                handicap: 0,
                tickMalus: 0,
                minStr: null,
            });
            expect(buildPropertyDerivedEffectData(item)).to.be.null;
        });

        it("omits the strength reference when minStr is null", () => {
            const item = makeItem("armor", {
                defenseBonus: 0,
                handicap: 2,
                tickMalus: 0,
                damageReduction: 0,
                minStr: null,
            });
            const effect = buildPropertyDerivedEffectData(item);
            expect(effect).to.not.be.null;
            expect(hasReference(findEntry(effect, "handicap.armor").serializedValue)).to.be.false;
        });

        it("attributeMalus stays live-reactive to strength after round-trip", async () => {
            const item = makeItem("armor", {
                defenseBonus: 0,
                handicap: 0,
                tickMalus: 0,
                damageReduction: 0,
                minStr: 13,
            });
            const effect = buildPropertyDerivedEffectData(item)!;
            const serialized = findEntry(effect, "handicap.armor").serializedValue;
            const deserialized = deserialize(serialized, () => ({ attributes: { strength: { value: 10 } } }) as any);
            expect(await evaluate(deserialized)).to.equal(3);
        });
    });

    describe("shield", () => {
        it("emits handicap.shield / tickmalus.shield with references per parsed minAttributes entry", () => {
            const item = makeItem("shield", {
                defenseBonus: 1,
                handicap: 1,
                tickMalus: 2,
                minAttributes: "BEW 13, AUS 12",
            });
            const effect = buildPropertyDerivedEffectData(item);
            expect(effect).to.not.be.null;
            expect(modifierPaths(effect)).to.have.members(["defense", "handicap.shield", "tickmalus.shield"]);
            const handicapRef = findEntry(effect, "handicap.shield").serializedValue;
            expect(hasReference(handicapRef)).to.be.true;
        });

        it("with empty minAttributes has no reference (just of(handicap))", () => {
            const item = makeItem("shield", { defenseBonus: 1, handicap: 1, tickMalus: 0, minAttributes: "" });
            const effect = buildPropertyDerivedEffectData(item);
            expect(effect).to.not.be.null;
            expect(hasReference(findEntry(effect, "handicap.shield").serializedValue)).to.be.false;
        });
    });

    describe("weapon", () => {
        it("emits a defense malus of 2 when the Unhandlich feature is present", () => {
            const item = makeItem("weapon", { features: { hasFeature: (f: string) => f === "Unhandlich" } });
            const effect = buildPropertyDerivedEffectData(item);
            expect(effect).to.not.be.null;
            expect(modifierPaths(effect)).to.deep.equal(["defense"]);
            expect(findEntry(effect, "defense").serializedValue).to.deep.equal(serialize(of(2)));
        });

        it("returns null when Unhandlich is absent", () => {
            const item = makeItem("weapon", { features: { hasFeature: () => false } });
            expect(buildPropertyDerivedEffectData(item)).to.be.null;
        });
    });

    describe("non-property item types", () => {
        it("returns null for equipment", () => {
            const item = makeItem("equipment", { modifier: "skills.acrobatics +2" });
            expect(buildPropertyDerivedEffectData(item)).to.be.null;
        });
    });
});
