import type SplittermondItem from "module/item/item";
import { stripSchwerpunktPrefix } from "module/activeEffect/sentinelSubstitution";
import { modifierTypeForItemType } from "module/activeEffect/modifierTypeResolver";
import { buildPropertyDerivedEffectData } from "module/activeEffect/propertyEffectBuilder";
import type { EffectCreationData } from "module/activeEffect/effectBuilder";
import type { ModifierEntry } from "module/activeEffect/types";
import type { IModifier, ModifierAttributes } from "module/modifiers";
import type { Expression } from "module/modifiers/expressions/scalar";
import { deserialize } from "module/modifiers/expressions/scalar/serialization";
import type { ActorProvider } from "module/modifiers/expressions/ActorProvider";
import { getFromRegistry } from "module/data/dataModelRegistry";
import { IllegalStateException } from "module/data/exceptions";
import type {StrengthDataModel} from "module/item/dataModel/StrengthDataModel";
import type {StatusEffectDataModel} from "module/item/dataModel/StatusEffectDataModel";

/**
 * Live fallback for the pre-ActiveEffect item modifier pathway: items that carry no
 * `autoGenerated` effect (i.e. items the effect migrations never reached) contribute
 * their `system.modifier` string and their property-derived modifiers to the owning
 * actor during actor preparation, exactly as before the ActiveEffect rework.
 *
 * @deprecated Remove when the modifier/property migrations are confirmed to cover all
 * world items, or at the next major release. Removal is a pure file deletion plus
 * reverting the delegation in `SplittermondItem.prepareActorData`.
 */

const debuggedItems = new Set<string>();

interface ModifierConstructor {
    new (
        path: string,
        value: Expression,
        attributes: ModifierAttributes,
        selectable: boolean,
        provider: ActorProvider
    ): IModifier;
}

interface HasModifierString {
    system: { modifier?: string | null };
}

interface HasMasteryPlaceholders {
    system: { skill?: string | null };
}

export function applyLiveItemModifiers(item: SplittermondItem): void {
    if (!item.actor) return;
    if (item.effects.some((effect) => effect.type === "autoGenerated")) return;
    if (isSuppressedByItemState(item)) return;
    logFallbackActive(item);
    applyStringModifiers(item);
    applyPropertyModifiers(item);
}

function applyStringModifiers(item: SplittermondItem): void {
    let modifierString = (item as HasModifierString).system.modifier ?? "";
    if (item.type === "mastery") {
        const name = stripSchwerpunktPrefix(item.name);
        modifierString = modifierString
            .split("${skill}")
            .join((item as HasMasteryPlaceholders).system.skill ?? "")
            .split("${name}")
            .join(name);
    }
    if (!modifierString.trim()) return;
    item.actor.addModifier(item, modifierString, modifierTypeForItemType(item.type) ?? "innate", multiplierFor(item));
}

function applyPropertyModifiers(item: SplittermondItem): void {
    const actor = item.actor;
    const provider: ActorProvider = () => actor;
    const multiplier = multiplierFor(item);
    for (const datum of buildPropertyDerivedEffectData(item)) {
        for (const entry of modifierEntriesOf(datum)) {
            actor.modifier.addModifier(buildModifierWrapper(entry, provider, multiplier));
        }
    }
}

function buildModifierWrapper(entry: ModifierEntry, provider: ActorProvider, multiplier: number): IModifier {
    const Impl = getFromRegistry(entry.implementation) as ModifierConstructor | undefined;
    if (!Impl) {
        throw new IllegalStateException(`Unknown modifier implementation: ${entry.implementation}`);
    }
    const baseValue = deserialize(entry.serializedValue, provider);
    return new Impl(entry.path, baseValue, entry.attributes, entry.selectable, provider).applyMultiplier(multiplier);
}

function modifierEntriesOf(datum: EffectCreationData): ModifierEntry[] {
    const { modifiers } = datum.system as { modifiers?: ModifierEntry[] };
    return modifiers ?? [];
}

function isSuppressedByItemState(item: SplittermondItem): boolean {
    switch (item.type) {
        case "weapon":
        case "shield":
        case "armor":
            return !(item.system as { equipped?: boolean | null }).equipped;
        case "spelleffect":
            return !(item.system as { active?: boolean | null }).active;
        default:
            return false;
    }
}

function multiplierFor(item: SplittermondItem): number {
    switch (item.type) {
        case "strength":
            return (item.system as StrengthDataModel).quantity ?? 1; //cast justified by case match
        case "statuseffect":
            return (item.system as StatusEffectDataModel).level ?? 1; //cast justified by case match
        default:
            return 1;
    }
}

function logFallbackActive(item: SplittermondItem): void {
    if (debuggedItems.has(item.uuid)) return;
    debuggedItems.add(item.uuid);
    console.debug(`Splittermond | Deprecated live item modifier fallback active for item ${item.uuid}`);
}
