import { afterEach, beforeEach, describe, it } from "mocha";
import { expect } from "chai";
import sinon, { SinonSandbox, SinonStub } from "sinon";
import { actualAddModifierFunction } from "module/actor/addModifierAdapter";
import { buildCostEffectData, buildScalarEffectData } from "module/activeEffect/effectBuilder";
import type { IModifierSource } from "module/modifiers/IModifierSource";
import type { AddModifierResult } from "module/modifiers/modifierAddition";
import { of } from "module/modifiers/expressions/scalar";
import { of as ofCost } from "module/modifiers/expressions/cost";
import { CostModifierDataModel } from "module/activeEffect/dataModel/CostModifierDataModel";
import { parseCostString } from "module/util/costs/costParser";

describe("AddModifierEffectDialog — onConfirm logic", () => {
    let sandbox: SinonSandbox;
    let addModifierStub: SinonStub;
    let createEmbeddedDocuments: SinonStub;
    let source: IModifierSource;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        addModifierStub = sandbox.stub();
        actualAddModifierFunction.self = addModifierStub as any;

        createEmbeddedDocuments = sandbox.stub().resolves([]);

        source = {
            name: "test modifier",
            actor: { uuid: "Actor.abc", isOwner: true } as any,
            uuid: "Actor.abc",
            isOwner: true,
        };
    });

    afterEach(() => {
        actualAddModifierFunction.self = null;
        sandbox.restore();
    });

    describe("buildScalarEffectData", () => {
        it("produces an object with the correct top-level shape for a scalar modifier", () => {
            const modifier = {
                groupId: "skills",
                value: of(2),
                attributes: { name: "skills +2" },
                selectable: false,
                effectType: "modifier" as const,
            };

            const result = buildScalarEffectData(modifier as any, "skills +2", "Actor.abc");

            expect(result.name).to.equal("skills +2");
            expect(result.origin).to.equal("Actor.abc");
            expect(result.type).to.equal("modifier");
            expect(result.transfer).to.be.true;
            expect(result.disabled).to.be.false;
            expect(result.flags).to.deep.include({
                splittermond: { autoGenerated: true, rawInput: "skills +2" },
            });
            expect(result.system).to.be.an("object");
        });
    });

    describe("buildCostEffectData", () => {
        it("produces an object with the correct top-level shape for a cost modifier", () => {
            const fakeSystem = { label: "kosten -1", serializedValue: { type: "amount" } };
            sandbox.stub(CostModifierDataModel, "init").returns(fakeSystem as any);

            const modifier = {
                label: "kosten -1",
                value: {} as any,
                skill: null,
                attributes: {},
                effectType: "costModifier" as const,
            };

            const result = buildCostEffectData(modifier as any, "kosten -1", "Actor.abc");

            expect(result.name).to.equal("kosten -1");
            expect(result.origin).to.equal("Actor.abc");
            expect(result.type).to.equal("costModifier");
            expect(result.transfer).to.be.true;
            expect(result.disabled).to.be.false;
            expect(result.flags).to.deep.include({
                splittermond: { autoGenerated: true, rawInput: "kosten -1" },
            });
            expect(result.system).to.equal(fakeSystem);
        });
    });

    describe("empty modifier string guard", () => {
        it("does not call createEmbeddedDocuments when modifier string is empty", async () => {
            const modifierString = "   ".trim();
            if (!modifierString) {
                // early return — replicates AddModifierEffectDialog.#onConfirm guard
            } else {
                const { modifiers, costModifiers } = addModifierStub(source, modifierString, null, 1);
                const effectDataArray = [
                    ...modifiers.map(({ modifier, rawFragment }: any) =>
                        buildScalarEffectData(modifier, rawFragment, source.uuid)
                    ),
                    ...costModifiers.map(({ modifier, rawFragment }: any) =>
                        buildCostEffectData(modifier, rawFragment, source.uuid)
                    ),
                ];
                if (effectDataArray.length > 0) {
                    await createEmbeddedDocuments("ActiveEffect", effectDataArray);
                }
            }

            expect(createEmbeddedDocuments.called).to.be.false;
            expect(addModifierStub.called).to.be.false;
        });

        it("does not call createEmbeddedDocuments when addModifier returns no effects", async () => {
            addModifierStub.returns({ modifiers: [], costModifiers: [] } satisfies AddModifierResult);

            const modifierString = "unknownpath +2";
            const { modifiers, costModifiers } = addModifierStub(source, modifierString, null, 1);
            const effectDataArray = [
                ...modifiers.map(({ modifier, rawFragment }: any) =>
                    buildScalarEffectData(modifier, rawFragment, source.uuid)
                ),
                ...costModifiers.map(({ modifier, rawFragment }: any) =>
                    buildCostEffectData(modifier, rawFragment, source.uuid)
                ),
            ];
            if (effectDataArray.length > 0) {
                await createEmbeddedDocuments("ActiveEffect", effectDataArray);
            }

            expect(createEmbeddedDocuments.called).to.be.false;
        });
    });
});

describe("AddModifierEffectDialog — onConfirm logic", () => {
    let sandbox: SinonSandbox;
    let addModifierStub: SinonStub;
    let createEmbeddedDocuments: SinonStub;
    let source: IModifierSource;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        addModifierStub = sandbox.stub();
        actualAddModifierFunction.self = addModifierStub as any;

        createEmbeddedDocuments = sandbox.stub().resolves([]);

        source = {
            name: "test modifier",
            actor: { uuid: "Actor.abc", isOwner: true } as any,
            uuid: "Actor.abc",
            isOwner: true,
        };
    });

    afterEach(() => {
        actualAddModifierFunction.self = null;
        sandbox.restore();
    });

    describe("buildScalarEffectData", () => {
        it("produces an object with the correct top-level shape for a scalar modifier", () => {
            const modifier = {
                groupId: "skills",
                value: of(2),
                attributes: { name: "skills +2" },
                selectable: false,
                effectType: "modifier" as const,
            };

            const result = buildScalarEffectData(modifier as any, "skills +2", "Actor.abc");

            expect(result.name).to.equal("skills +2");
            expect(result.origin).to.equal("Actor.abc");
            expect(result.type).to.equal("modifier");
            expect(result.transfer).to.be.true;
            expect(result.disabled).to.be.false;
            expect(result.flags).to.deep.include({
                splittermond: { autoGenerated: true, rawInput: "skills +2" },
            });
            expect(result.system).to.be.an("object");
        });
    });

    describe("buildCostEffectData", () => {
        it("produces an object with the correct top-level shape for a cost modifier", () => {
            const modifier = {
                label: "kosten -1",
                value: ofCost(parseCostString("-1").asModifier()),
                skill: null,
                attributes: {},
                effectType: "costModifier" as const,
            };

            const result = buildCostEffectData(modifier, "kosten -1", "Actor.abc");

            expect(result.name).to.equal("kosten -1");
            expect(result.origin).to.equal("Actor.abc");
            expect(result.type).to.equal("costModifier");
            expect(result.transfer).to.be.true;
            expect(result.disabled).to.be.false;
            expect(result.flags).to.deep.include({
                splittermond: { autoGenerated: true, rawInput: "kosten -1" },
            });
            expect(result.system).to.be.an("object");
        });
    });

    describe("empty modifier string guard", () => {
        it("does not call createEmbeddedDocuments when modifier string is empty", async () => {
            addModifierStub.returns({ modifiers: [], costModifiers: [] } satisfies AddModifierResult);

            // Replicate the guard from AddModifierEffectDialog.#onConfirm
            const modifierString = "   ".trim();
            if (!modifierString) {
                // early return — createEmbeddedDocuments should never be reached
            } else {
                const { modifiers, costModifiers } = addModifierStub(source, modifierString, null, 1);
                const effectDataArray = [
                    ...modifiers.map(({ modifier, rawFragment }: any) =>
                        buildScalarEffectData(modifier, rawFragment, source.uuid)
                    ),
                    ...costModifiers.map(({ modifier, rawFragment }: any) =>
                        buildCostEffectData(modifier, rawFragment, source.uuid)
                    ),
                ];
                if (effectDataArray.length > 0) {
                    await createEmbeddedDocuments("ActiveEffect", effectDataArray);
                }
            }

            expect(createEmbeddedDocuments.called).to.be.false;
            expect(addModifierStub.called).to.be.false;
        });

        it("does not call createEmbeddedDocuments when addModifier returns no effects", async () => {
            addModifierStub.returns({ modifiers: [], costModifiers: [] } satisfies AddModifierResult);

            const modifierString = "unknownpath +2";
            const { modifiers, costModifiers } = addModifierStub(source, modifierString, null, 1);
            const effectDataArray = [
                ...modifiers.map(({ modifier, rawFragment }: any) =>
                    buildScalarEffectData(modifier, rawFragment, source.uuid)
                ),
                ...costModifiers.map(({ modifier, rawFragment }: any) =>
                    buildCostEffectData(modifier, rawFragment, source.uuid)
                ),
            ];
            if (effectDataArray.length > 0) {
                await createEmbeddedDocuments("ActiveEffect", effectDataArray);
            }

            expect(createEmbeddedDocuments.called).to.be.false;
        });
    });
});
