import SplittermondItemSheet from "module/item/sheets/item-sheet";
import { ApplicationRenderContext, TEMPLATE_BASE_PATH } from "module/data/SplittermondApplication";
import { addModifierEffects, isGenerated } from "module/activeEffect/effectBuilder";
import type { EffectCardContext } from "module/activeEffect";
import { buildEffectCardContext, SplittermondActiveEffect } from "module/activeEffect";
import { SplittermondActiveEffectCreationDialog } from "module/activeEffect/sheets/SplittermondActiveEffectCreationDialog";
import { getAddModifier } from "module/item/item";
import type { HandlebarsRenderOptions } from "module/api/Application";
import ApplicationRenderOptions = foundry.applications.types.ApplicationRenderOptions;

interface ItemEffectCardContext extends EffectCardContext {
    id: string;
    name: string;
    disabled: boolean;
    autoGenerated: boolean;
}

export default class SplittermondItemEffectsSheet extends SplittermondItemSheet {
    static DEFAULT_OPTIONS = {
        ...super.DEFAULT_OPTIONS,
        actions: {
            ...super.DEFAULT_OPTIONS.actions,
            "add-effect": SplittermondItemEffectsSheet.#addEffect,
            "open-effect-dialog": SplittermondItemEffectsSheet.#openEffectDialog,
            "delete-effect": SplittermondItemEffectsSheet.#deleteEffect,
            "toggle-effect": SplittermondItemEffectsSheet.#toggleEffect,
            "edit-effect": SplittermondItemEffectsSheet.#editEffect,
        },
    };

    static TABS = {
        primary: {
            tabs: [
                { id: "editor", group: "primary", label: "splittermond.description" },
                { id: "properties", group: "primary", label: "splittermond.properties" },
                { id: "effects", group: "primary", label: "splittermond.effects" },
            ],
            initial: "editor",
        },
    };

    static PARTS = {
        ...super.PARTS,
        effects: {
            template: `${TEMPLATE_BASE_PATH}/sheets/item/effects.hbs`,
            scrollable: [""],
            classes: ["scrollable", "scrollable-margin-mitigation"],
        },
    };

    protected override get allowsActiveEffectDrop(): boolean {
        return true;
    }

    override async _preparePartContext(
        partId: string,
        context: ApplicationRenderContext,
        options: Partial<HandlebarsRenderOptions>
    ): Promise<any> {
        const data = (await super._preparePartContext(partId, context, options)) as ApplicationRenderContext;
        switch (partId) {
            case "effects":
                return await this.#prepareEffectsPart(data);
        }
        return data;
    }

    async #prepareEffectsPart(context: ApplicationRenderContext): Promise<ApplicationRenderContext> {
        const effects: ItemEffectCardContext[] = (this.item.effects as unknown as SplittermondActiveEffect[]).map(
            (e) => ({
                id: e.id,
                name: e.name,
                disabled: e.disabled,
                autoGenerated: isGenerated(e),
                ...buildEffectCardContext(e),
            })
        );
        context.effects = effects;
        context.modifierHelpText = await this.htmlEnricher(this.localizer.localize("splittermond.modificatorHelpText"));
        return context;
    }

    protected override async _onRender(
        context: ApplicationRenderContext,
        options: ApplicationRenderOptions
    ): Promise<void> {
        await super._onRender(context, options);

        const modifierInput = this.element.querySelector<HTMLInputElement>(".effect-modifier-input");
        if (modifierInput) {
            modifierInput.addEventListener("keydown", (event: KeyboardEvent) => {
                if (event.key === "Enter") {
                    event.preventDefault();
                    event.stopPropagation();
                    const addButton = this.element.querySelector<HTMLButtonElement>("[data-action='add-effect']");
                    addButton?.click();
                }
            });
        }
    }

    override async _onDropActiveEffect(event: DragEvent, document: SplittermondActiveEffect) {
        const newDocument = await super._onDropActiveEffect(event, document);
        if (!newDocument) return null;
        if (isGenerated(newDocument)) {
            newDocument.setAutoGenerated(false);
        }
        return newDocument;
    }

    static async #addEffect(this: SplittermondItemEffectsSheet, _event: Event, _target: HTMLElement): Promise<void> {
        const input = this.element.querySelector<HTMLInputElement>(".effect-modifier-input");
        if (!input) return;
        const modifierString = input.value.trim();
        if (!modifierString) return;
        const modifierFn = getAddModifier();
        if (!modifierFn) return;
        const effects = await addModifierEffects(modifierFn, this.item, modifierString);
        if (effects) {
            await Promise.all(effects.map((e) => e.setAutoGenerated(false)));
        }
        input.value = "";
        this.render();
    }

    static async #deleteEffect(this: SplittermondItemEffectsSheet, _event: Event, target: HTMLElement): Promise<void> {
        const card = target.closest<HTMLElement>("[data-effect-id]");
        const effectId = card?.dataset.effectId;
        if (!effectId) return;
        await this.item.deleteEmbeddedDocuments("ActiveEffect", [effectId]);
        this.render();
    }

    static async #toggleEffect(this: SplittermondItemEffectsSheet, _event: Event, target: HTMLElement): Promise<void> {
        const card = target.closest<HTMLElement>("[data-effect-id]");
        const effectId = card?.dataset.effectId;
        if (!effectId) return;
        const effect = this.item.effects.get(effectId);
        if (!effect) return;
        await effect.update({ disabled: !effect.disabled });
        this.render();
    }

    static async #editEffect(this: SplittermondItemEffectsSheet, _event: Event, target: HTMLElement): Promise<void> {
        const card = target.closest<HTMLElement>("[data-effect-id]");
        const effectId = card?.dataset.effectId;
        if (!effectId) return;
        const effect = this.item.effects.get(effectId);
        effect?.sheet?.render({ force: true });
    }

    static async #openEffectDialog(this: SplittermondItemEffectsSheet): Promise<void> {
        await SplittermondActiveEffectCreationDialog.show(SplittermondActiveEffect, {}, { parent: this.item });
    }
}
