import { expect } from "chai";
import sinon from "sinon";
import { JSDOM } from "jsdom";
import SplittermondItem from "module/item/item";
import SplittermondItemSheet from "module/item/sheets/item-sheet";
import SplittermondItemEffectsSheet from "module/item/sheets/item-effects-sheet";
import { SplittermondActiveEffect } from "module/activeEffect";
import { foundryApi } from "module/api/foundryApi";

describe("Item sheet tabs after active effect drops", () => {
    const sandbox = sinon.createSandbox();
    beforeEach(() => sandbox.stub(foundryApi, "localize").callsFake((key) => key));
    afterEach(() => sandbox.restore());

    for (const type of ["modifier", "autoGenerated"] as const) {
        for (const succeeds of [true, false]) {
            it(`${succeeds ? "reveals" : "does not navigate for"} a ${type} effect drop`, async () => {
                const item = sandbox.createStubInstance(SplittermondItem);
                item.type = "weapon";
                const sheet = new SplittermondItemEffectsSheet({ document: item });
                Object.defineProperty(sheet, "element", { value: new JSDOM().window.document.body });
                Object.defineProperty(sheet, "rendered", { value: true });
                sheet.element.innerHTML =
                    '<section data-tab="effects"><li class="effect-card" data-effect-id="created"></li></section>';
                const row = sheet.element.querySelector("li")!;
                const animate = sandbox.stub();
                sandbox.define(row, "scrollIntoView", sandbox.stub());
                sandbox.define(row, "animate", animate);
                const changeTab = sandbox.stub(sheet, "changeTab");
                const render = sandbox.spy(sheet, "render");
                const effect = sandbox.createStubInstance(SplittermondActiveEffect);
                effect.type = type;
                effect.toObject = sandbox.stub<[source?: boolean], { type: string }>().returns({ type });
                const created = sandbox.createStubInstance(SplittermondActiveEffect);
                Object.defineProperty(created, "id", { value: "created" });
                const result = succeeds ? created : null;
                const inheritedDrop = sandbox
                    .stub(SplittermondItemSheet.prototype, "_onDropActiveEffect")
                    .resolves(result);
                item.createEmbeddedDocuments = sandbox
                    .stub<
                        Parameters<SplittermondItem["createEmbeddedDocuments"]>,
                        ReturnType<SplittermondItem["createEmbeddedDocuments"]>
                    >()
                    .resolves(succeeds ? [created] : []);

                expect(await sheet._onDropActiveEffect(new Event("drop") as DragEvent, effect)).to.equal(result);

                expect(changeTab.callCount).to.equal(succeeds ? 1 : 0);
                expect(animate.callCount).to.equal(succeeds ? 1 : 0);
                expect(render.called).to.be.false;
                expect(inheritedDrop.called).to.equal(type === "modifier");
                if (type === "autoGenerated") {
                    expect(item.createEmbeddedDocuments.firstCall.args[1]).to.deep.equal([{ type: "modifier" }]);
                }
                if (succeeds) expect(changeTab.firstCall.args).to.deep.equal(["effects", "primary", { force: true }]);
            });
        }
    }
});
