import { describe, it, beforeEach, afterEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonSandbox, type SinonStub } from "sinon";
import SplittermondItemSheet from "module/item/sheets/item-sheet";
import { foundryApi } from "module/api/foundryApi";
import { splittermond } from "module/config";

function makeEffect(opts: { id?: string; name?: string; disabled?: boolean; autoGenerated?: boolean }) {
    const { id = "eff-1", name = "Test Effect", disabled = false, autoGenerated = true } = opts;
    return {
        id,
        name,
        disabled,
        getFlag: sinon
            .stub()
            .callsFake((scope: string, key: string) =>
                scope === "splittermond" && key === "autoGenerated" ? autoGenerated : undefined
            ),
    };
}

function makeSheet(effects: ReturnType<typeof makeEffect>[], enricher?: SinonStub) {
    const resolvedEnricher = enricher ?? sinon.stub().resolves("");
    const mockItem = { type: "weapon", effects, system: { description: "" } };
    const localizer = { localize: sinon.stub().returns("") };
    return new SplittermondItemSheet(
        { document: mockItem },
        foundryApi.utils.resolveProperty,
        localizer,
        splittermond,
        resolvedEnricher
    );
}

describe("SplittermondItemSheet — effects part context", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        sandbox.stub(foundryApi, "localize").callsFake((s: string) => s);
    });

    afterEach(() => sandbox.restore());

    it("returns an empty effects array when the item has no effects", async () => {
        const sheet = makeSheet([]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects).to.deep.equal([]);
    });

    it("includes autoGenerated and native effects", async () => {
        const auto = makeEffect({ id: "auto-id", autoGenerated: true });
        const manual = makeEffect({ id: "manual-id", autoGenerated: false });
        const sheet = makeSheet([auto, manual]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects).to.have.length(2);
        expect(result.effects[0].id).to.equal("auto-id");
    });

    it("maps each effect to the shape {id, name, disabled}", async () => {
        const eff = makeEffect({ id: "e1", name: "My Effect", disabled: true, autoGenerated: true });
        const sheet = makeSheet([eff]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects[0]).to.deep.equal({ id: "e1", name: "My Effect", disabled: true });
    });

    it("sets modifierHelpText from the enricher output", async () => {
        const enricher = sinon.stub().resolves("<p>help</p>");
        const sheet = makeSheet([], enricher);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.modifierHelpText).to.equal("<p>help</p>");
    });

    it("preserves unrelated context properties", async () => {
        const sheet = makeSheet([]);
        const result = await sheet._preparePartContext("effects", { unrelated: "value" }, {});
        expect(result.unrelated).to.equal("value");
    });

    it("disabled flag is false for an enabled effect", async () => {
        const eff = makeEffect({ disabled: false, autoGenerated: true });
        const sheet = makeSheet([eff]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects[0].disabled).to.equal(false);
    });
});
