import { describe, it, beforeEach, afterEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonStub } from "sinon";
import type { SinonSandbox } from "sinon";
import SplittermondItemEffectsSheet from "module/item/sheets/item-effects-sheet";
import SplittermondSpellSheet from "module/item/sheets/spell-sheet";
import { foundryApi } from "module/api/foundryApi";
import { splittermond } from "module/config";

function makeEffect(opts: {
    id?: string;
    name?: string;
    disabled?: boolean;
    autoGenerated?: boolean;
    expired?: boolean;
}) {
    const { id = "eff-1", name = "Test Effect", disabled = false, autoGenerated = true, expired = false } = opts;
    return {
        id,
        name,
        disabled,
        autoGenerated,
        getFlag: sinon
            .stub()
            .callsFake((scope: string, key: string) =>
                scope === "splittermond" && key === "autoGenerated" ? autoGenerated : undefined
            ),
        isSuppressed: false,
        type: "modifier" as const,
        durationMode: "permanent" as const,
        duration: {
            expired,
            value: null,
            units: "",
        },
    } as {
        id: string;
        name: string;
        disabled: boolean;
        autoGenerated: boolean;
        getFlag: SinonStub;
        isSuppressed: boolean;
        type: "modifier";
        durationMode: "permanent";
        duration: { expired: boolean; value: null; units: string };
    };
}

function makeSheet(effects: ReturnType<typeof makeEffect>[], enricher?: SinonStub) {
    return makeTypedSheet("weapon", effects, enricher);
}

function makeTypedSheet(itemType: string, effects: ReturnType<typeof makeEffect>[], enricher?: SinonStub) {
    const resolvedEnricher = enricher ?? sinon.stub().resolves("");
    const mockItem = { type: itemType, effects, system: { description: "" } };
    const localizer = { localize: sinon.stub().returns("") };
    return new SplittermondItemEffectsSheet(
        { document: mockItem },
        foundryApi.utils.resolveProperty,
        localizer,
        splittermond,
        resolvedEnricher
    );
}

function makeDropEvent(payload: unknown): DragEvent {
    const data = payload === undefined ? undefined : JSON.stringify(payload);
    return {
        dataTransfer: { getData: () => data ?? "" },
    } as unknown as DragEvent;
}

function makeSpellSheet(effects: ReturnType<typeof makeEffect>[], enricher?: SinonStub) {
    const resolvedEnricher = enricher ?? sinon.stub().resolves("");
    const mockItem = { type: "spell", effects, system: { description: "" } };
    const localizer = { localize: sinon.stub().returns("") };
    return new SplittermondSpellSheet(
        { document: mockItem },
        foundryApi.utils.resolveProperty,
        localizer,
        splittermond,
        resolvedEnricher
    );
}

describe("SplittermondItemEffectsSheet — effects part context", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        sandbox.stub(foundryApi, "localize").callsFake((s: string) => s);
    });

    afterEach(() => sandbox.restore());

    it("returns an empty effects array when the item has no effects", async () => {
        const sheet = makeSheet([]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects).to.deep.equal([]);
    });

    it("includes autoGenerated and native effects", async () => {
        const auto = makeEffect({ id: "auto-id", autoGenerated: true });
        const manual = makeEffect({ id: "manual-id", autoGenerated: false });
        const sheet = makeSheet([auto, manual]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects).to.have.length(2);
        expect(result.effects[0].id).to.equal("auto-id");
    });

    it("maps each effect to the shape {id, name, disabled}", async () => {
        const eff = makeEffect({ id: "e1", name: "My Effect", disabled: true, autoGenerated: false });
        const sheet = makeSheet([eff]);
        const result = await sheet._preparePartContext("effects", {}, {});
        const actual = result.effects[0];
        expect(actual.id).to.equal("e1");
        expect(actual.name).to.equal("My Effect");
        expect(actual.disabled).to.equal(true);
        expect(actual.badges).to.deep.equal([]);
        expect(actual.type).to.equal("modifier");
        expect(actual.typeCssClass).to.equal("");
        expect(actual.showTicks).to.equal(false);
        expect(actual.timeToExpirationDisplay).to.be.null;
    });

    it("sets modifierHelpText from the enricher output", async () => {
        const enricher = sinon.stub().resolves("<p>help</p>");
        const sheet = makeSheet([], enricher);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.modifierHelpText).to.equal("<p>help</p>");
    });

    it("preserves unrelated context properties", async () => {
        const sheet = makeSheet([]);
        const result = await sheet._preparePartContext("effects", { unrelated: "value" }, {});
        expect(result.unrelated).to.equal("value");
    });

    it("disabled flag is false for an enabled effect", async () => {
        const eff = makeEffect({ disabled: false, autoGenerated: true });
        const sheet = makeSheet([eff]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects[0].disabled).to.equal(false);
    });
});

describe("SplittermondItemSheet — effects block on unsupported item types", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        sandbox.stub(foundryApi, "localize").callsFake((s: string) => s);
    });

    afterEach(() => sandbox.restore());

    it("returns the effects part context unchanged for a spell-typed sheet", async () => {
        const sheet = makeSpellSheet([]);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects).to.be.undefined;
        expect(result.modifierHelpText).to.be.undefined;
    });

    it("warns and blocks the drop when an ActiveEffect is dropped on a spell-typed sheet", async () => {
        const warnStub = sandbox.stub(foundryApi, "warnUser");
        const sheet = makeSpellSheet([]);
        await sheet._onDropActiveEffect(makeDropEvent({ type: "ActiveEffect", uuid: "some-uuid" }), {
            type: "ActiveEffect",
            uuid: "some-uuid",
        });
        expect(warnStub.calledOnce).to.be.true;
        expect(warnStub.firstCall.args[0]).to.equal("splittermond.activeEffect.error.itemTypeEffectsNotSupported");
    });

    it("still populates the effects array for a weapon-typed sheet", async () => {
        const sheet = makeTypedSheet("weapon", []);
        const result = await sheet._preparePartContext("effects", {}, {});
        expect(result.effects).to.deep.equal([]);
        expect(result.modifierHelpText).to.equal("");
    });
});

describe("SplittermondSpellSheet — static PARTS/TABS do not include effects entries", () => {
    it("PARTS does not include the effects key", () => {
        expect(SplittermondSpellSheet.PARTS).to.not.have.property("effects");
    });

    it("TABS.primary.tabs does not include an effects entry", () => {
        const ids = SplittermondSpellSheet.TABS.primary.tabs.map((t) => t.id);
        expect(ids).to.not.include("effects");
    });

    it("PARTS preserves the non-effects keys from the base", () => {
        expect(SplittermondSpellSheet.PARTS).to.have.property("header");
        expect(SplittermondSpellSheet.PARTS).to.have.property("editor");
        expect(SplittermondSpellSheet.PARTS).to.have.property("properties");
    });

    it("TABS preserves the non-effects tabs from the base", () => {
        const ids = SplittermondSpellSheet.TABS.primary.tabs.map((t) => t.id);
        expect(ids).to.include("editor");
        expect(ids).to.include("properties");
    });
});
