import { foundryApi } from "module/api/foundryApi";
import { MigrationBuilder, type MigrationResult } from "module/migrations/Migrator";
import { getAddModifier } from "module/item/item";
import { addModifierEffects } from "module/activeEffect/effectBuilder";
import { modifierTypeForItemType } from "module/activeEffect/modifierTypeResolver";
import type { IAddModifier } from "module/actor/addModifierAdapter";
import type { IModifierSource } from "module/modifiers/IModifierSource";

export const MIGRATION_FLAG_SCOPE = "splittermond";
export const MIGRATION_FLAG_KEY = "modifierToEffectMigrationDone";

/**
 * Version stamp written to `flags.splittermond.modifierMigrationVersion` on every
 * effect produced by this migration, so future migrations can identify the batch.
 * Bump when the transport logic changes and re-running is desired.
 */
export const MODIFIER_TO_EFFECT_MIGRATION_VERSION = "1";

export type { MigrationResult };

/**
 * Transport one item's `system.modifier` string into persistent `modifier`-type
 * ActiveEffects — one effect per parsed modifier fragment, mirroring the
 * `autoGenerated` grouping but with a durable type that survives item updates.
 *
 * Idempotent: the entry condition is a non-empty `system.modifier`. After a
 * successful transport the field is cleared to `""`, so a re-run (even forced)
 * finds nothing to parse and creates no duplicate effects. Clearing the field
 * also triggers the item's `autoGenerated` rebuild, which removes any prior
 * autoGenerated effects derived from the old string — leaving only the new
 * `modifier`-type effects (plus property-derived autoGenerated effects).
 *
 * The `addModifier` parser is injected so the per-item logic is unit-testable
 * without the Foundry-bound `getAddModifier` singleton.
 */
export async function migrateModifierToEffects(item: Item, addModifier: IAddModifier | null): Promise<boolean> {
    const modifierString = getModifierString(item);
    if (!modifierString.trim()) return false;

    if (!addModifier) return false;

    const modifierType = modifierTypeForItemType(item.type);

    await item.setFlag("splittermond", "systemModifier", modifierString);
    await item.update({ "system.modifier": "" });

    await addModifierEffects(
        addModifier,
        item as unknown as IModifierSource,
        modifierString,
        modifierType,
        "modifier",
        { modifierMigrationVersion: MODIFIER_TO_EFFECT_MIGRATION_VERSION }
    );

    await item.setFlag("splittermond", "systemModifier", null);
    return true;
}

function getModifierString(item: Item) {
    const modifierString = item.system?.modifier || item.getFlag("splittermond", "systemModifier");
    return modifierString ?? "";
}

function modifierToEffectMigrationBuilder(): MigrationBuilder<Item> {
    return new MigrationBuilder<Item>(MIGRATION_FLAG_KEY)
        .withWorldCollection(() => foundryApi.collections.items)
        .withDocumentClass("Item")
        .withMigrationProcess((item) => migrateModifierToEffects(item, getAddModifier()))
        .withI18nPrefix("splittermond.migration.modifierToEffectMigration");
}

const productionMigration = modifierToEffectMigrationBuilder();

export const migrationDoneFlag: typeof productionMigration.migrationDoneFlag = productionMigration.migrationDoneFlag;

const migrator = productionMigration.build();

export async function runModifierToEffectMigration(options?: { force?: boolean }): Promise<MigrationResult> {
    return migrator.run(options);
}

export async function promptAndRunModifierToEffectMigration(): Promise<void> {
    return migrator.promptAndRun();
}
