import { foundryApi } from "module/api/foundryApi";
import { MigrationBuilder, type MigrationResult } from "module/migrations/Migrator";
import { isSplittermondPack } from "module/item/migrations/splittermondPackFilter";
import SplittermondItem, { getAddModifier } from "module/item/item";
import { addModifierEffects } from "module/activeEffect/effectBuilder";
import { modifierTypeForItemType } from "module/activeEffect/modifierTypeResolver";
import type { IAddModifier } from "module/actor/addModifierAdapter";
import { splittermond } from "module/config";
import { copyCompendiumEffectToItem } from "module/activeEffect/compendiumEffectAssignment";
import { stripSchwerpunktPrefix } from "module/activeEffect/sentinelSubstitution";

export const MIGRATION_FLAG_SCOPE = "splittermond";

/**
 * Version stamp written to `flags.splittermond.modifierMigrationVersion` on every
 * effect produced by this migration. The version is also part of the completion
 * setting so worlds that already completed an older run receive the updated
 * migration once.
 */
export const MODIFIER_TO_EFFECT_MIGRATION_VERSION = 3;
export const MIGRATION_FLAG_KEY = `modifierToEffectMigrationV${MODIFIER_TO_EFFECT_MIGRATION_VERSION}Done`;

export type { MigrationResult };

/**
 * Transport one item's `system.modifier` string into persistent `modifier`-type
 * ActiveEffects — one effect per parsed modifier fragment, mirroring the
 * `autoGenerated` grouping but with a durable type that survives item updates.
 *
 * Idempotent: the entry condition is a non-empty `system.modifier`. After a
 * successful transport the field is cleared to `""`, so a re-run (even forced)
 * finds nothing to parse and creates no duplicate effects. Clearing the field
 * also triggers the item's `autoGenerated` rebuild, which removes any prior
 * autoGenerated effects derived from the old string — leaving only the new
 * `modifier`-type effects (plus property-derived autoGenerated effects).
 *
 * The `addModifier` parser is injected so the per-item logic is unit-testable
 * without the Foundry-bound `getAddModifier` singleton.
 */
export async function migrateModifierToEffects(
    item: SplittermondItem,
    addModifier: IAddModifier | null
): Promise<boolean> {
    const modifierString = getModifierString(item);

    if (!modifierString && ["strength", "mastery"].includes(item.type)) {
        const alreadyMigrated = item.effects.some(
            (effect) => effect.getFlag("splittermond", "modifierMigrationVersion") != null
        );
        if (alreadyMigrated) return false;
        const lowercaseName = item.name.trim().toLowerCase();
        if (lowercaseName in splittermond.modifier) {
            const effectUuid = splittermond.modifier[lowercaseName as keyof typeof splittermond.modifier];
            const alreadyAssigned = item.effects.some((effect) => effect.getFlag("core", "sourceId") === effectUuid);
            if (alreadyAssigned) return false;
            const created = await copyCompendiumEffectToItem(item, effectUuid);
            return created.length > 0;
        }
    }
    if (!modifierString.trim()) return false;
    if (!addModifier) return false;

    const resolvedModifierString = resolveMasteryPlaceholders(item, modifierString);
    if (resolvedModifierString === null) return false;

    const modifierType = modifierTypeForItemType(item.type);
    const parseResult = addModifier(item, resolvedModifierString, modifierType);
    if (parseResult.hasErrors) return false;

    await item.setFlag("splittermond", "systemModifier", modifierString);
    await item.update({ "system.modifier": "" });

    await addModifierEffects(() => parseResult, item, resolvedModifierString, modifierType, "modifier", {
        modifierMigrationVersion: MODIFIER_TO_EFFECT_MIGRATION_VERSION,
    });

    await item.setFlag("splittermond", "systemModifier", null);
    return true;
}

function getModifierString(item: Item) {
    const modifierString = item.system?.modifier || item.getFlag("splittermond", "systemModifier");
    return modifierString ?? "";
}

/**
 * Mastery modifier strings may contain template sentinels. Embedded masteries
 * have a concrete skill and can be transported after substitution. Library
 * templates without a selected skill must keep their source string so the
 * normal item-assignment workflow can substitute it later.
 */
function resolveMasteryPlaceholders(item: SplittermondItem, modifierString: string): string | null {
    if (item.type !== "mastery") return modifierString;

    let resolved = modifierString.split("${name}").join(stripSchwerpunktPrefix(item.name));
    if (!resolved.includes("${skill}")) return resolved;

    const skill = (item.system as { skill?: string | null }).skill;
    if (!skill) return null;
    resolved = resolved.split("${skill}").join(skill);
    return resolved;
}

function modifierToEffectMigrationBuilder(): MigrationBuilder<SplittermondItem> {
    return new MigrationBuilder<SplittermondItem>(MIGRATION_FLAG_KEY)
        .withWorldCollection(generateWorldCollection)
        .withCompendiumFilter(isSplittermondPack)
        .withDocumentClass("Item")
        .withMigrationProcess((item) => migrateModifierToEffects(item, getAddModifier()))
        .withI18nPrefix("splittermond.migration.modifierToEffectMigration");
}

const productionMigration = modifierToEffectMigrationBuilder();

export const migrationDoneFlag: typeof productionMigration.migrationDoneFlag = productionMigration.migrationDoneFlag;

const migrator = productionMigration.build();

export async function runModifierToEffectMigration(options?: { force?: boolean }): Promise<MigrationResult> {
    return migrator.run(options);
}

export async function promptAndRunModifierToEffectMigration(): Promise<void> {
    return migrator.promptAndRun();
}

function* generateWorldCollection(): Generator<FoundryDocument> {
    yield* foundryApi.collections.items;
    yield* foundryApi.collections.actors;
    yield* foundryApi.scenes;
}
