import { QuenchBatchContext } from "@ethaks/fvtt-quench";
import {
    migrateModifierToEffects,
    MODIFIER_TO_EFFECT_MIGRATION_VERSION,
} from "module/item/migrations/modifierToEffectMigration";
import { getAddModifier } from "module/item/item";
import { foundryApi } from "module/api/foundryApi";
import { passesEventually } from "../../util";

declare const foundry: any;
declare const Item: { deleteDocuments(ids: string[]): Promise<unknown> };

interface EffectLike {
    id: string;
    type: string;
    getFlag(scope: string, key: string): unknown;
}

interface ItemLike {
    id: string;
    type: string;
    uuid: string;
    system: { modifier?: string | null };
    effects: Collection<EffectLike>;
    update(data: object): Promise<unknown>;
}

interface Collection<T> {
    filter(predicate: (e: T) => boolean): T[];
    get(id: string): T | undefined;
    size: number;
}

interface CompendiumLike {
    documentName: string;
    metadata: { system?: string };
    locked: boolean;
    title: string;
    getDocuments(): Promise<ItemLike[]>;
    importDocument(item: object): Promise<unknown>;
    deleteCompendium(): Promise<void>;
}

function equipmentData(modifier: string): Record<string, unknown> {
    return {
        type: "equipment",
        name: `Modifier Migration Test ${modifier}`,
        system: { modifier },
    };
}

function modifierTypeEffects(item: ItemLike): EffectLike[] {
    return item.effects.filter((e) => e.type === "modifier");
}

function autoGeneratedEffects(item: ItemLike): EffectLike[] {
    return item.effects.filter((e) => e.type === "autoGenerated");
}

export function modifierToEffectMigrationTest(context: QuenchBatchContext) {
    const { describe, it, expect, afterEach, beforeEach } = context;

    describe("migrateModifierToEffects processor", function () {
        this.timeout(15000);

        let worldItemIds: string[];

        beforeEach(() => {
            worldItemIds = [];
        });

        afterEach(async () => {
            for (const id of worldItemIds) {
                await Item.deleteDocuments([id]);
            }
        });

        it("transports a world item's system.modifier into a modifier-type effect with the version flag", async () => {
            const created = (await foundryApi.createItem(equipmentData("acrobatics +2"))) as unknown as ItemLike;
            worldItemIds.push(created.id);

            await passesEventually(
                () => {
                    expect(
                        autoGeneratedEffects(created).length,
                        "item rebuilds autoGenerated effects from the string on create"
                    ).to.be.greaterThan(0);
                },
                1500,
                50
            );

            const migrated = await migrateModifierToEffects(created as unknown as Item, getAddModifier());

            void expect(migrated, "processor reports a migrated item").to.be.true;

            await passesEventually(
                () => {
                    expect(created.system.modifier, "system.modifier is cleared").to.equal("");
                },
                1500,
                50
            );

            const effects = modifierTypeEffects(created);
            expect(effects.length, "one modifier-type effect is created from the fragment").to.equal(1);
            expect(effects[0].getFlag("splittermond", "modifierMigrationVersion")).to.equal(
                MODIFIER_TO_EFFECT_MIGRATION_VERSION
            );
            expect(
                autoGeneratedEffects(created).length,
                "autoGenerated effects from the old string are gone after the rebuild"
            ).to.equal(0);
        });

        it("is idempotent: a re-run creates no duplicate effects", async () => {
            const created = (await foundryApi.createItem(equipmentData("defense +1"))) as unknown as ItemLike;
            worldItemIds.push(created.id);

            await migrateModifierToEffects(created as unknown as Item, getAddModifier());

            await passesEventually(() => expect(created.system.modifier).to.equal(""), 1500, 50);

            const effectsAfterFirst = modifierTypeEffects(created).length;
            expect(effectsAfterFirst).to.equal(1);

            const second = await migrateModifierToEffects(created as unknown as Item, getAddModifier());
            void expect(second, "second run finds nothing to transport").to.be.false;

            await passesEventually(
                () =>
                    expect(
                        modifierTypeEffects(created).length,
                        "second run does not create duplicate modifier-type effects"
                    ).to.equal(effectsAfterFirst),
                1500,
                50
            );
            expect(created.system.modifier, "string stays cleared").to.equal("");
        });

        it("leaves items without a modifier string untouched", async () => {
            const created = (await foundryApi.createItem(equipmentData(""))) as unknown as ItemLike;
            worldItemIds.push(created.id);

            const migrated = await migrateModifierToEffects(created as unknown as Item, getAddModifier());

            expect(migrated, "nothing to transport counts as not migrated").to.be.false;
            expect(created.system.modifier, "empty string stays empty").to.equal("");
            expect(
                modifierTypeEffects(created).length,
                "no modifier-type effect is created when there was nothing to transport"
            ).to.equal(0);
        });

        describe("compendium round-trip", function () {
            let testCompendium: CompendiumLike;

            beforeEach(async () => {
                testCompendium = (await foundry.documents.collections.CompendiumCollection.createCompendium({
                    type: "Item",
                    label: "Modifier Migration Test Pack",
                })) as CompendiumLike;
                const worldItem = (await foundryApi.createItem(equipmentData("acrobatics +2"))) as unknown as {
                    id: string;
                };
                await testCompendium.importDocument(worldItem);
                await Item.deleteDocuments([worldItem.id]);
            });

            afterEach(async () => {
                if (testCompendium) {
                    await testCompendium.deleteCompendium();
                }
            });

            it("migrates the compendium item and persists a modifier-type effect", async () => {
                const docs = await testCompendium.getDocuments();
                expect(docs).to.have.lengthOf(1);
                const doc = docs[0] as unknown as Item;

                const migrated = await migrateModifierToEffects(doc, getAddModifier());

                void expect(migrated, "processor reports a migrated compendium item").to.be.true;

                const reloaded = (await testCompendium.getDocuments())[0];
                expect(reloaded.system.modifier, "compendium item modifier string is cleared").to.equal("");

                const effects = modifierTypeEffects(reloaded);
                expect(effects.length, "compendium item carries the migrated modifier-type effect").to.equal(1);
                expect(effects[0].getFlag("splittermond", "modifierMigrationVersion")).to.equal(
                    MODIFIER_TO_EFFECT_MIGRATION_VERSION
                );
            });
        });
    });
}
