import { QuenchBatchContext } from "@ethaks/fvtt-quench";
import { SplittermondActiveEffect } from "module/activeEffect";
import { evaluate } from "module/modifiers/expressions/scalar";
import { withActor } from "./fixtures";
import { passesEventually } from "../util";

export function activeEffectMultiplierTest(context: QuenchBatchContext) {
    const { describe, it, expect } = context;

    describe("ActiveEffect multiplier at read time (asModifiers x effect.multiplier)", () => {
        it(
            "should apply strength.quantity to the effect's modifier value at read time",
            withActor(async (actor) => {
                const [item] = await actor.createEmbeddedDocuments("Item", [
                    {
                        type: "strength",
                        name: "Starker Zaubertrank",
                        system: { modifier: "bonuscap +2", quantity: 3 },
                    },
                ]);

                await passesEventually(
                    () => {
                        expect(
                            item.effects.filter((e: { getFlag: (s: string, k: string) => unknown }) =>
                                e.getFlag("splittermond", "autoGenerated")
                            ).length
                        ).to.be.greaterThan(0);
                    },
                    1500,
                    50
                );

                const effect = item.effects.find((e: { getFlag: (s: string, k: string) => unknown }) =>
                    e.getFlag("splittermond", "autoGenerated")
                ) as SplittermondActiveEffect;
                expect(effect, "auto-generated effect should exist").to.not.be.undefined;
                expect(effect.multiplier, "strength item with quantity 3 yields multiplier 3").to.equal(3);

                const modifiers = effect.asModifiers;
                expect(modifiers).to.have.length(1);
                expect(await evaluate(modifiers[0].value), "base 2 * multiplier 3 = 6").to.equal(6);
            })
        );

        it(
            "should apply statuseffect.level to the effect's modifier value at read time",
            withActor(async (actor) => {
                const [item] = await actor.createEmbeddedDocuments("Item", [
                    {
                        type: "statuseffect",
                        name: "Fluch",
                        system: { modifier: "bonuscap +2", level: 4 },
                    },
                ]);

                await passesEventually(
                    () => {
                        expect(
                            item.effects.filter((e: { getFlag: (s: string, k: string) => unknown }) =>
                                e.getFlag("splittermond", "autoGenerated")
                            ).length
                        ).to.be.greaterThan(0);
                    },
                    1500,
                    50
                );

                const effect = item.effects.find((e: { getFlag: (s: string, k: string) => unknown }) =>
                    e.getFlag("splittermond", "autoGenerated")
                ) as SplittermondActiveEffect;
                expect(effect, "auto-generated effect should exist").to.not.be.undefined;
                expect(effect.multiplier, "statuseffect item with level 4 yields multiplier 4").to.equal(4);

                const modifiers = effect.asModifiers;
                expect(modifiers).to.have.length(1);
                expect(await evaluate(modifiers[0].value), "base 2 * multiplier 4 = 8").to.equal(8);
            })
        );

        it(
            "should return multiplier 1 for an item type without quantity/level (weapon)",
            withActor(async (actor) => {
                const [item] = await actor.createEmbeddedDocuments("Item", [
                    {
                        type: "weapon",
                        name: "Schwert",
                        system: { modifier: "bonuscap +2", equipped: true },
                    },
                ]);

                await passesEventually(
                    () => {
                        expect(
                            item.effects.filter((e: { getFlag: (s: string, k: string) => unknown }) =>
                                e.getFlag("splittermond", "autoGenerated")
                            ).length
                        ).to.be.greaterThan(0);
                    },
                    1500,
                    50
                );

                const effect = item.effects.find((e: { getFlag: (s: string, k: string) => unknown }) =>
                    e.getFlag("splittermond", "autoGenerated")
                ) as SplittermondActiveEffect;
                expect(effect, "auto-generated effect should exist").to.not.be.undefined;
                expect(effect.multiplier).to.equal(1);

                const modifiers = effect.asModifiers;
                expect(modifiers).to.have.length(1);
                expect(await evaluate(modifiers[0].value), "base 2 unchanged (multiplier 1)").to.equal(2);
            })
        );
    });
}
