import { QuenchBatchContext } from "@ethaks/fvtt-quench";
import { SplittermondActiveEffect } from "module/activeEffect";
import { regenerateBakedMultiplierEffects } from "module/activeEffect/migrations/regenerateBakedMultiplierEffects";
import { evaluate, of, times } from "module/modifiers/expressions/scalar";
import { serialize } from "module/modifiers/expressions/scalar/serialization";
import { foundryApi } from "module/api/foundryApi";
import { withActor } from "./fixtures";
import { passesEventually } from "../util";

const MIGRATION_FLAG_SCOPE = "splittermond";
const MIGRATION_FLAG_KEY = "bakedMultiplierV1MigrationDone";

function oldBakedSerializedValue() {
    return serialize(times(of(3), of(2)));
}

function serializedValueOf(effect: SplittermondActiveEffect): unknown {
    const system = effect.system as { modifiers?: Array<{ serializedValue?: unknown }> };
    return system.modifiers?.[0]?.serializedValue;
}

export function bakedMultiplierMigrationTest(context: QuenchBatchContext) {
    const { describe, it, expect, afterEach } = context;

    describe("regenerateBakedMultiplierEffects migration", () => {
        afterEach(async () => {
            await foundryApi.settings.set(MIGRATION_FLAG_SCOPE, MIGRATION_FLAG_KEY, false);
        });

        it(
            "should regenerate a baked-in strength.quantity multiplier effect to the un-baked form",
            withActor(async (actor) => {
                await foundryApi.settings.set(MIGRATION_FLAG_SCOPE, MIGRATION_FLAG_KEY, false);

                const [item] = await actor.createEmbeddedDocuments("Item", [
                    {
                        type: "strength",
                        name: "Starker Zaubertrank",
                        system: { modifier: "bonuscap +2", quantity: 3 },
                    },
                ]);

                await passesEventually(
                    () => {
                        expect(
                            item.effects.filter((e: { getFlag: (s: string, k: string) => unknown }) =>
                                e.getFlag("splittermond", "autoGenerated")
                            ).length
                        ).to.be.greaterThan(0);
                    },
                    1500,
                    50
                );

                const effect = item.effects.find((e: { getFlag: (s: string, k: string) => unknown }) =>
                    e.getFlag("splittermond", "autoGenerated")
                ) as SplittermondActiveEffect;

                expect(effect, "auto-generated effect should exist").to.not.be.undefined;
                expect(await evaluate(effect.asModifiers[0].value), "pre-migration evaluates to 6").to.equal(6);

                await effect.update({
                    system: {
                        modifiers: [
                            {
                                ...(effect.system as { modifiers: object[] }).modifiers[0],
                                serializedValue: oldBakedSerializedValue(),
                            },
                        ],
                    },
                });

                await passesEventually(
                    () => {
                        expect(JSON.stringify(serializedValueOf(effect))).to.equal(
                            JSON.stringify(oldBakedSerializedValue())
                        );
                    },
                    1500,
                    50
                );
                expect(
                    await evaluate(effect.asModifiers[0].value),
                    "baked-in value double-counts the multiplier under late evaluation (3 baked * 3 read-time = 18)"
                ).to.equal(18);

                await regenerateBakedMultiplierEffects();

                await passesEventually(
                    () => {
                        const e = item.effects.find((ef: { getFlag: (s: string, k: string) => unknown }) =>
                            ef.getFlag("splittermond", "autoGenerated")
                        ) as SplittermondActiveEffect | undefined;
                        expect(e, "migrated auto-generated effect should exist").to.not.be.undefined;
                        expect(JSON.stringify(serializedValueOf(e!))).to.equal(JSON.stringify(serialize(of(2))));
                    },
                    1500,
                    50
                );

                const migratedEffect = item.effects.find((ef: { getFlag: (s: string, k: string) => unknown }) =>
                    ef.getFlag("splittermond", "autoGenerated")
                ) as SplittermondActiveEffect;

                expect(migratedEffect.multiplier, "multiplier is still 3 at read time").to.equal(3);
                expect(await evaluate(migratedEffect.asModifiers[0].value), "post-migration evaluates to 6").to.equal(
                    6
                );
            })
        );
    });
}
