export const modifiers = {
    addsplinter: "Compendium.splittermond.activeeffects.ActiveEffect.mG0LtZMOsGQx6Ahu",
    sturdy: "Compendium.splittermond.activeeffects.ActiveEffect.M3ORNA2ElcHW0JJY",
    resistbody: "Compendium.splittermond.activeeffects.ActiveEffect.18Mi2zrAiIuXlScd",
    resistmind: "Compendium.splittermond.activeeffects.ActiveEffect.kZXMfyuLm0UDJ2jS",
    focuspool: "Compendium.splittermond.activeeffects.ActiveEffect.GaLh4kIc204Alrs3",
    highini: "Compendium.splittermond.activeeffects.ActiveEffect.xgkSINBE5qy7Xnlg",
    resistpain: "Compendium.splittermond.activeeffects.ActiveEffect.uNrtmHcuFkwNPEfJ",
    resistpain1: "Compendium.splittermond.activeeffects.ActiveEffect.uNrtmHcuFkwNPEfJ",
    resistpain2: "Compendium.splittermond.activeeffects.ActiveEffect.uNrtmHcuFkwNPEfJ",
    swift: "Compendium.splittermond.activeeffects.ActiveEffect.cacSlyacJD7fe731",
    armour1: "Compendium.splittermond.activeeffects.ActiveEffect.OmNxUPDpwlYpJFHH",
    shield1: "Compendium.splittermond.activeeffects.ActiveEffect.hrCmkwkZwcLv1w9m",
    armour2: "Compendium.splittermond.activeeffects.ActiveEffect.Si6rbjHuRkBYtCSy",
    shield2: "Compendium.splittermond.activeeffects.ActiveEffect.f77rby6jjAkUGUYN",
    "schnelle schildabwehr": "Compendium.splittermond.activeeffects.ActiveEffect.CibhTH1PeXiYuDyw",
    "beidhändige abwehr": "Compendium.splittermond.activeeffects.ActiveEffect.dsSkEOvFM6ip7Twv",
    flashreflexes: "Compendium.splittermond.activeeffects.ActiveEffect.xgkSINBE5qy7Xnlg",
    goodreflexes: "Compendium.splittermond.activeeffects.ActiveEffect.eaD1S9OIw2qQVmza",
    arcanespeed: "Compendium.splittermond.activeeffects.ActiveEffect.cacSlyacJD7fe731",
    sprinter: "Compendium.splittermond.activeeffects.ActiveEffect.cacSlyacJD7fe731",
    focusregen: "Compendium.splittermond.activeeffects.ActiveEffect.d5ln2ZJ2swvd8NVY",
    liferegen: "Compendium.splittermond.activeeffects.ActiveEffect.RNPZy0bij7LweUfJ",
    naturalarmor: "Compendium.splittermond.activeeffects.ActiveEffect.kZuPEAdt7YU5cnmM",
    schmerzimmunität: "Compendium.splittermond.activeeffects.ActiveEffect.jpfSNsJnQoVf762h",
    schmerzresistenz: "Compendium.splittermond.activeeffects.ActiveEffect.uNrtmHcuFkwNPEfJ",
    schwächlich: "Compendium.splittermond.activeeffects.ActiveEffect.Scju7NUJE8EA8h8U",
    "erhöhte fokusregeneration": "Compendium.splittermond.activeeffects.ActiveEffect.d5ln2ZJ2swvd8NVY",
    "erhöhte lebensregeneration": "Compendium.splittermond.activeeffects.ActiveEffect.RNPZy0bij7LweUfJ",
    "erhöhter fokuspool": "Compendium.splittermond.activeeffects.ActiveEffect.GaLh4kIc204Alrs3",
    flink: "Compendium.splittermond.activeeffects.ActiveEffect.cacSlyacJD7fe731",
    "hoher geistiger widerstand": "Compendium.splittermond.activeeffects.ActiveEffect.kZXMfyuLm0UDJ2jS",
    "hoher körperlicher widerstand": "Compendium.splittermond.activeeffects.ActiveEffect.18Mi2zrAiIuXlScd",
    robust: "Compendium.splittermond.activeeffects.ActiveEffect.M3ORNA2ElcHW0JJY",
    "verbesserte initiative": "Compendium.splittermond.activeeffects.ActiveEffect.xgkSINBE5qy7Xnlg",
    "zusätzliche splitterpunkte": "Compendium.splittermond.activeeffects.ActiveEffect.mG0LtZMOsGQx6Ahu",
    "stabile magie": "Compendium.splittermond.activeeffects.ActiveEffect.fcz0bo1PdDn66xdH",
    blitzreflexe: "Compendium.splittermond.activeeffects.ActiveEffect.xgkSINBE5qy7Xnlg",
    "gute reflexe": "Compendium.splittermond.activeeffects.ActiveEffect.eaD1S9OIw2qQVmza",
    "rüstungsträger i": "Compendium.splittermond.activeeffects.ActiveEffect.OmNxUPDpwlYpJFHH",
    "rüstungsträger 1": "Compendium.splittermond.activeeffects.ActiveEffect.OmNxUPDpwlYpJFHH",
    "rüstungsträger ii": "Compendium.splittermond.activeeffects.ActiveEffect.Si6rbjHuRkBYtCSy",
    "rüstungsträger 2": "Compendium.splittermond.activeeffects.ActiveEffect.Si6rbjHuRkBYtCSy",
    "schildträger i": "Compendium.splittermond.activeeffects.ActiveEffect.hrCmkwkZwcLv1w9m",
    "schildträger 1": "Compendium.splittermond.activeeffects.ActiveEffect.hrCmkwkZwcLv1w9m",
    "schildträger ii": "Compendium.splittermond.activeeffects.ActiveEffect.f77rby6jjAkUGUYN",
    "schildträger 2": "Compendium.splittermond.activeeffects.ActiveEffect.f77rby6jjAkUGUYN",
    "natürlicher rüstungsschutz": "Compendium.splittermond.activeeffects.ActiveEffect.kZuPEAdt7YU5cnmM",
} as const;
export type SplittermondModifier = keyof typeof modifiers;
