const fightingSkills = ["melee", "slashing", "chains", "blades", "longrange", "staffs", "throwing"] as const;
const generalSkills = [
    "acrobatics",
    "alchemy",
    "leadership",
    "arcanelore",
    "athletics",
    "performance",
    "diplomacy",
    "clscraft",
    "empathy",
    "determination",
    "dexterity",
    "history",
    "craftmanship",
    "heal",
    "stealth",
    "hunting",
    "countrylore",
    "nature",
    "eloquence",
    "locksntraps",
    "swim",
    "seafaring",
    "streetlore",
    "animals",
    "survival",
    "perception",
    "endurance",
] as const;
const magicSkills = [
    "antimagic",
    "controlmagic",
    "motionmagic",
    "insightmagic",
    "stonemagic",
    "firemagic",
    "healmagic",
    "illusionmagic",
    "combatmagic",
    "lightmagic",
    "naturemagic",
    "shadowmagic",
    "fatemagic",
    "protectionmagic",
    "enhancemagic",
    "deathmagic",
    "transformationmagic",
    "watermagic",
    "windmagic",
] as const;
export const skillGroups = {
    essential: ["acrobatics", "athletics", "determination", "stealth", "perception", "endurance"],
    ranged: ["throwing", "longrange"],
    social: ["eloquence", "diplomacy", "empathy", "determination", "leadership"],
    fighting: fightingSkills,
    general: generalSkills,
    magic: magicSkills,
    all: [...generalSkills, ...fightingSkills, ...magicSkills],
} as const satisfies Record<string, readonly SplittermondSkill[]>;

export type SplittermondMagicSkill = (typeof magicSkills)[number];
export type SplittermondFightingSkill = (typeof fightingSkills)[number];
export type SplittermondGeneralSkill = (typeof generalSkills)[number];
export type SplittermondSkill = SplittermondFightingSkill | SplittermondGeneralSkill | SplittermondMagicSkill;
