import type { ParsedModifier } from "module/modifiers/parsing";
import type { ModifierType } from "module/modifiers";
import type SplittermondItem from "module/item/item";
import { parseModifiers } from "module/modifiers/parsing";

interface EffectCreationData {
    name: string;
    transfer: boolean;
    disabled: boolean;
    changes: Array<{
        key: string;
        value: string;
        mode: number;
    }>;
    flags: Record<string, unknown>;
}

/**
 * Build ActiveEffect creation data from a single parsed modifier.
 */
function buildEffectData(
    parsed: ParsedModifier,
    modifierType: ModifierType,
    multiplier: number,
    rawFragment: string
): EffectCreationData {
    const valueStr = parsed.attributes.value != null ? String(parsed.attributes.value) : "0";
    // @ts-ignore -- CONST is a Foundry global
    const customMode: number = CONST.ACTIVE_EFFECT_MODES.CUSTOM;
    return {
        name: rawFragment.trim(),
        transfer: true,
        disabled: false,
        changes: [
            {
                key: parsed.path,
                value: valueStr,
                mode: customMode,
            },
        ],
        flags: {
            splittermond: {
                autoGenerated: true,
                modifierType: modifierType,
                multiplier: multiplier,
                rawInput: rawFragment.trim(),
                attributes: { ...parsed.attributes },
            },
        },
    };
}

/**
 * Rebuild the auto-generated ActiveEffects on an item from its modifier string.
 * Deletes existing auto-generated effects, then creates new ones from the current string.
 *
 * @param item The item whose modifier string should be parsed into effects.
 * @param modifierType The ModifierType to tag effects with.
 * @param multiplier The multiplier (e.g. quantity, level).
 */
export async function rebuildModifierEffects(
    item: SplittermondItem,
    modifierType: ModifierType,
    multiplier: number = 1
): Promise<void> {
    const modifierString: string = (item.system as any).modifier ?? "";

    // 1. Delete existing auto-generated effects
    const existingAutoEffects = (item as any).effects.filter(
        (e: any) => e.getFlag("splittermond", "autoGenerated") === true
    );
    const idsToDelete: string[] = existingAutoEffects.map((e: any) => e.id).filter(Boolean);
    if (idsToDelete.length > 0) {
        await (item as any).deleteEmbeddedDocuments("ActiveEffect", idsToDelete);
    }

    // 2. Parse the modifier string
    if (!modifierString.trim()) return;

    const { modifiers, errors } = parseModifiers(modifierString);
    if (errors.length > 0) {
        console.warn(`Splittermond | Errors parsing modifiers for item "${item.name}":`, errors);
    }

    // Split the original string to get raw fragments for each modifier
    const rawFragments = splitRawFragments(modifierString);

    // 3. Build effect data for each parsed modifier
    const effectDataArray: EffectCreationData[] = modifiers.map((parsed, index) => {
        const rawFragment = rawFragments[index] ?? parsed.path;
        return buildEffectData(parsed, modifierType, multiplier, rawFragment);
    });

    if (effectDataArray.length > 0) {
        await (item as any).createEmbeddedDocuments("ActiveEffect", effectDataArray);
    }
}

/**
 * Split a modifier string into its comma-separated raw fragments,
 * respecting quoted strings (same logic as the parser's splitModifiers).
 */
function splitRawFragments(modifiers: string): string[] {
    const result: string[] = [];
    let mode: "TOP" | "ATTRIBUTE" = "TOP";
    let currentDelimiter: string | null = null;
    let start = 0;
    for (let i = 0; i < modifiers.length; i++) {
        const char = modifiers.charAt(i);
        if (mode === "TOP" && ["'", '"'].includes(char)) {
            mode = "ATTRIBUTE";
            currentDelimiter = char;
        } else if (mode === "ATTRIBUTE" && char === currentDelimiter) {
            mode = "TOP";
            currentDelimiter = null;
        } else if (char === "," && mode === "TOP") {
            result.push(modifiers.substring(start, i).trim());
            start = i + 1;
        }
    }
    result.push(modifiers.substring(start).trim());
    return result;
}
