import { parseModifiers } from "../modifiers/parsing/parser.ts";

/**
 * Build ActiveEffect creation data from a single parsed modifier.
 * @param {import("../modifiers/parsing").ParsedModifier} parsed
 * @param {string|null} modifierType
 * @param {number} multiplier
 * @param {string} rawFragment
 * @returns {object}
 */
function buildEffectData(parsed, modifierType, multiplier, rawFragment) {
    const valueStr = parsed.attributes.value != null ? String(parsed.attributes.value) : "0";
    return {
        name: rawFragment.trim(),
        transfer: true,
        disabled: false,
        changes: [{
            key: parsed.path,
            value: valueStr,
            mode: CONST.ACTIVE_EFFECT_MODES.CUSTOM,
        }],
        flags: {
            splittermond: {
                autoGenerated: true,
                modifierType: modifierType,
                multiplier: multiplier,
                rawInput: rawFragment.trim(),
                attributes: { ...parsed.attributes },
            },
        },
    };
}

/**
 * Rebuild the auto-generated ActiveEffects on an item from its modifier string.
 * Deletes existing auto-generated effects, then creates new ones from the current string.
 *
 * @param {Item} item The item whose modifier string should be parsed into effects.
 * @param {string|null} modifierType The ModifierType to tag effects with.
 * @param {number} [multiplier=1] The multiplier (e.g. quantity, level).
 */
export async function rebuildModifierEffects(item, modifierType, multiplier = 1) {
    const modifierString = item.system.modifier ?? "";

    // 1. Delete existing auto-generated effects
    const existingAutoEffects = item.effects.filter(
        (e) => e.getFlag("splittermond", "autoGenerated") === true
    );
    const idsToDelete = existingAutoEffects.map((e) => e.id).filter(Boolean);
    if (idsToDelete.length > 0) {
        await item.deleteEmbeddedDocuments("ActiveEffect", idsToDelete);
    }

    // 2. Parse the modifier string
    if (!modifierString.trim()) return;

    const { modifiers, errors } = parseModifiers(modifierString);
    if (errors.length > 0) {
        console.warn(`Splittermond | Errors parsing modifiers for item "${item.name}":`, errors);
    }

    // Split the original string to get raw fragments for each modifier
    const rawFragments = splitRawFragments(modifierString);

    // 3. Build effect data for each parsed modifier
    const effectDataArray = modifiers.map((parsed, index) => {
        const rawFragment = rawFragments[index] ?? parsed.path;
        return buildEffectData(parsed, modifierType, multiplier, rawFragment);
    });

    if (effectDataArray.length > 0) {
        await item.createEmbeddedDocuments("ActiveEffect", effectDataArray);
    }
}

/**
 * Split a modifier string into its comma-separated raw fragments,
 * respecting quoted strings (same logic as the parser's splitModifiers).
 * @param {string} modifiers
 * @returns {string[]}
 */
function splitRawFragments(modifiers) {
    const result = [];
    let mode = "TOP";
    let currentDelimiter = null;
    let start = 0;
    for (let i = 0; i < modifiers.length; i++) {
        const char = modifiers.charAt(i);
        if (mode === "TOP" && ["'", '"'].includes(char)) {
            mode = "ATTRIBUTE";
            currentDelimiter = char;
        } else if (mode === "ATTRIBUTE" && char === currentDelimiter) {
            mode = "TOP";
            currentDelimiter = null;
        } else if (char === "," && mode === "TOP") {
            result.push(modifiers.substring(start, i).trim());
            start = i + 1;
        }
    }
    result.push(modifiers.substring(start).trim());
    return result;
}
