import type { EffectType } from "module/activeEffect/dataModel/effectTypes";
import type { DurationMode } from "module/activeEffect/SplittermondActiveEffect";

export type EffectCardEffect = {
    isSuppressed: boolean;
    disabled: boolean;
    autoGenerated: boolean;
    type: EffectType | "base";
    durationMode: DurationMode;
    duration: {
        expired: boolean;
        value: number | null;
        units: string;
        label?: string | null;
        start?: { round?: number };
    };
};

export type EffectCardBadge = {
    icon: string;
    tooltipKey: string;
    cssClass: string;
};

export type EffectCardContext = {
    type: EffectType | "base";
    typeCssClass: string;
    badges: EffectCardBadge[];
    timeToExpirationDisplay: string | null;
    showTicks: boolean;
    isInactive: boolean;
};

const HIGHLIGHTED_TYPES: Record<string, boolean> = {
    spellEffect: true,
    attackEffect: true,
    spellEnhancedEffect: true,
};

function isInactiveEffect(effect: EffectCardEffect): boolean {
    return effect.disabled || effect.isSuppressed || effect.duration.expired || effect.autoGenerated;
}

export function buildEffectCardContext(effect: EffectCardEffect): EffectCardContext {
    const badges: EffectCardBadge[] = [];

    if (effect.autoGenerated) {
        badges.push({
            icon: "fa-wand-magic-sparkles",
            tooltipKey: "splittermond.activeEffect.badge.generatedFromItemProperty",
            cssClass: "badge-generated",
        });
    }

    if (effect.isSuppressed) {
        badges.push({
            icon: "fa-link-slash",
            tooltipKey: "splittermond.activeEffect.badge.suppressed",
            cssClass: "badge-suppressed",
        });
    }

    if (effect.duration.expired) {
        badges.push({
            icon: "fa-hourglass-end",
            tooltipKey: "splittermond.activeEffect.badge.expired",
            cssClass: "badge-expired",
        });
    }

    if (effect.durationMode === "channelled") {
        badges.push({
            icon: "fa-arrows-to-circle",
            tooltipKey: "splittermond.activeEffect.badge.channelled",
            cssClass: "badge-channelled",
        });
    }

    const isTimed = effect.durationMode === "timed" && !effect.duration.expired;
    return {
        type: effect.type,
        typeCssClass: effect.type in HIGHLIGHTED_TYPES ? `effect-type-${effect.type}` : "",
        badges,
        timeToExpirationDisplay: effect.duration.label ?? null,
        showTicks: isTimed,
        isInactive: isInactiveEffect(effect),
    };
}
