import type { ModifierType } from "module/modifiers";
import type { ICostModifier } from "module/util/costs/spellCostManagement";
import type SplittermondItem from "module/item/item";
import type { IModifierSource } from "module/modifiers/IModifierSource";
import type { AddModifierResult, TaggedModifier } from "module/modifiers/modifierAddition";
import type { EffectType } from "module/activeEffect/dataModel/effectTypes";
import { serialize } from "module/modifiers/expressions/scalar/serialization";
import { CostModifierDataModel } from "./dataModel/CostModifierDataModel";

type AddModifierFn = (item: IModifierSource, str: string, type: ModifierType) => AddModifierResult;

interface HasModifierString {
    system: { modifier: string | null };
}

interface EffectCreationData {
    name: string;
    origin: string;
    type: EffectType;
    transfer: boolean;
    disabled: boolean;
    system: object;
    flags: Record<string, unknown>;
}

export function buildScalarEffectData(tagged: TaggedModifier, origin: string): EffectCreationData {
    const system = {
        modifiers: [
            {
                path: tagged.modifier.groupId,
                serializedValue: serialize(tagged.modifier.value),
                implementation: tagged.implementation,
                selectable: tagged.modifier.selectable,
                attributes: tagged.modifier.attributes,
            },
        ],
        costModifiers: [],
    };
    return {
        name: tagged.rawFragment,
        origin,
        type: "modifier",
        transfer: true,
        disabled: false,
        system,
        flags: {
            splittermond: {
                autoGenerated: true,
                rawInput: tagged.rawFragment,
            },
        },
    };
}

export function buildCostEffectData(modifier: ICostModifier, rawFragment: string, origin: string): EffectCreationData {
    const costModifierEntry = CostModifierDataModel.init(
        modifier.label,
        modifier.value,
        modifier.skill,
        modifier.attributes
    );
    const system = {
        modifiers: [],
        costModifiers: [costModifierEntry],
    };
    return {
        name: rawFragment,
        origin,
        type: "modifier",
        transfer: true,
        disabled: false,
        system,
        flags: {
            splittermond: {
                autoGenerated: true,
                rawInput: rawFragment,
            },
        },
    };
}

/**
 * Add ActiveEffects from a modifier string to an item, without deleting existing effects.
 */
export async function addModifierEffects(
    addModifier: AddModifierFn,
    item: IModifierSource,
    modifierString: string,
    modifierType: ModifierType = "magic" as ModifierType
): Promise<void> {
    if (!modifierString.trim()) return;

    const { modifiers, costModifiers } = addModifier(item, modifierString, modifierType);

    const effectDataArray: EffectCreationData[] = [
        ...modifiers.map((tagged) => buildScalarEffectData(tagged, item.uuid)),
        ...costModifiers.map(({ modifier, rawFragment }) => buildCostEffectData(modifier, rawFragment, item.uuid)),
    ];

    if (effectDataArray.length > 0) {
        await (
            item as unknown as { createEmbeddedDocuments(t: string, d: object[]): Promise<unknown> }
        ).createEmbeddedDocuments("ActiveEffect", effectDataArray);
    }
}

export function isGenerated(effect: { getFlag(scope: string, key: string): unknown }) {
    return !!effect.getFlag("splittermond", "autoGenerated");
}

/**
 * Rebuild the auto-generated ActiveEffects on an item from its modifier string.
 * Deletes existing auto-generated effects, then creates new ones from the current string.
 *
 * If `modifierString` is omitted, the item's `system.modifier` field is used. Callers that
 * need to substitute template placeholders (e.g. masteries' `${skill}`/`${name}`) must pass
 * the already-substituted string explicitly.
 */
export async function rebuildModifierEffects(
    addModifier: AddModifierFn,
    item: SplittermondItem,
    modifierType: ModifierType,
    modifierString?: string
): Promise<void> {
    const resolvedModifierString: string = modifierString ?? (item as HasModifierString).system.modifier ?? "";

    const existingAutoEffects = item.effects.filter(isGenerated);
    const idsToDelete: string[] = existingAutoEffects.map((e) => e.id);
    if (idsToDelete.length > 0) {
        await item.deleteEmbeddedDocuments("ActiveEffect", idsToDelete);
    }

    if (!resolvedModifierString.trim()) return;

    const { modifiers, costModifiers } = addModifier(item, resolvedModifierString, modifierType);

    const effectDataArray: EffectCreationData[] = [
        ...modifiers.map((tagged) => buildScalarEffectData(tagged, item.uuid)),
        ...costModifiers.map(({ modifier, rawFragment }) => buildCostEffectData(modifier, rawFragment, item.uuid)),
    ];

    if (effectDataArray.length > 0) {
        await item.createEmbeddedDocuments("ActiveEffect", effectDataArray);
    }
}
