import { foundryApi } from "module/api/foundryApi";
import { isFirstActiveGM } from "module/util/foundryUserUtils";

export const MIGRATION_FLAG_SCOPE = "splittermond";
export const MIGRATION_FLAG_KEY = "autoGeneratedTypeMigrationDone";
const AUTOGENERATED_FLAG_SCOPE = "splittermond";
const AUTOGENERATED_FLAG_KEY = "autoGenerated";

export interface MigratableEffect {
    readonly id: string;
    readonly type: string;
    getFlag(scope: string, key: string): unknown;
    update(data: object): Promise<unknown>;
}

export interface EffectHost {
    effects?: Iterable<MigratableEffect>;
}

function isFlagBearing(effect: MigratableEffect): boolean {
    return effect.getFlag(AUTOGENERATED_FLAG_SCOPE, AUTOGENERATED_FLAG_KEY) === true;
}

/**
 * Collect every effect on the given hosts that still carries the legacy
 * `flags.splittermond.autoGenerated` marker. Exposed for unit tests so they
 * can pass plain mock hosts without stubbing `foundryApi.collections`.
 */
export function collectFlagBearingEffects(hosts: Iterable<EffectHost>): MigratableEffect[] {
    const collected: MigratableEffect[] = [];
    for (const host of hosts) {
        const effects = host.effects;
        if (!effects) continue;
        for (const effect of effects) {
            if (!isFlagBearing(effect)) continue;
            collected.push(effect);
        }
    }
    return collected;
}

async function migrateEffects(effects: MigratableEffect[]): Promise<void> {
    for (const effect of effects) {
        await effect.update({
            type: "autoGenerated",
            flags: { splittermond: { "-=autoGenerated": null } },
        });
    }
}

/**
 * One-shot migration: flip every effect still carrying the legacy
 * `flags.splittermond.autoGenerated === true` marker to `type: "autoGenerated"`
 * and delete the flag. Sibling to {@link regenerateBakedMultiplierEffects};
 * must run before it on the `ready` hook because the baked-multiplier
 * migration uses `isGenerated` (now type-based) to find effects.
 *
 * Idempotent: guarded by a world-scope setting. No-op (but still sets the
 * done flag) when nothing matches.
 */
export async function migrateAutoGeneratedFlag(): Promise<void> {
    if (!isFirstActiveGM(foundryApi.currentUser, foundryApi.users)) return;

    if (foundryApi.settings.get<boolean>(MIGRATION_FLAG_SCOPE, MIGRATION_FLAG_KEY) === true) return;

    const hosts: EffectHost[] = [];
    for (const actor of foundryApi.collections.actors) {
        hosts.push(actor);
        for (const item of (actor as { items?: Iterable<EffectHost> }).items ?? []) {
            hosts.push(item);
        }
    }
    for (const item of foundryApi.collections.items) {
        hosts.push(item);
    }

    const effects = collectFlagBearingEffects(hosts);
    await migrateEffects(effects);

    await foundryApi.settings.set(MIGRATION_FLAG_SCOPE, MIGRATION_FLAG_KEY, true);
}
