import { describe, it, beforeEach, afterEach } from "mocha";
import { expect } from "chai";
import sinon, { type SinonSandbox, type SinonStub } from "sinon";
import { applyLiveItemModifiers } from "module/item/deprecated/liveItemModifierFallback";
import { foundryApi } from "module/api/foundryApi";
import { evaluate } from "module/modifiers/expressions/scalar";
import { Modifier } from "module/modifiers/impl/modifier";
import type SplittermondItem from "module/item/item";

interface FakeActor {
    attributes: { strength: { value: number } };
    addModifier: SinonStub;
    modifier: { addModifier(modifier: Modifier): void };
    addedModifiers: Modifier[];
}

interface FakeEffect {
    type: string;
}

function makeActor(strength = 10): FakeActor {
    const addedModifiers: Modifier[] = [];
    return {
        attributes: { strength: { value: strength } },
        addModifier: sinon.stub(),
        addedModifiers,
        modifier: {
            addModifier: (modifier: Modifier) => {
                addedModifiers.push(modifier);
            },
        },
    };
}

function makeItem(
    type: string,
    system: Record<string, unknown>,
    actor: FakeActor | null,
    effects: FakeEffect[] = [],
    name = "Test Item"
): SplittermondItem {
    return { type, uuid: "Item.test-uuid", name, actor, system, effects } as unknown as SplittermondItem;
}

function addedModifierByPath(actor: FakeActor, path: string): Modifier {
    const modifier = actor.addedModifiers.find((m) => m.path === path);
    if (!modifier) throw new Error(`no modifier registered for path ${path}`);
    return modifier;
}

async function registeredValue(actor: FakeActor, path: string) {
    return evaluate(addedModifierByPath(actor, path).value);
}

const ARMOR_SYSTEM = {
    equipped: true,
    defenseBonus: 2,
    damageReduction: 0,
    handicap: 1,
    tickMalus: 0,
    minStr: 13,
};

describe("applyLiveItemModifiers", () => {
    let sandbox: SinonSandbox;

    beforeEach(() => {
        sandbox = sinon.createSandbox();
        sandbox.stub(console, "debug");
        sandbox.stub(foundryApi, "localize").callsFake((key: string) => {
            const label = key.match(/^splittermond\.activeEffect\.propertyEffectName\.([^.]+)$/);
            return label ? label[1] : key;
        });
    });

    afterEach(() => sandbox.restore());

    it("registers armor defense and handicap/tickmalus with the strength-dependent malus", async () => {
        const actor = makeActor(10);
        const item = makeItem("armor", ARMOR_SYSTEM, actor);

        applyLiveItemModifiers(item);

        expect(actor.addedModifiers.map((m) => m.path)).to.have.members([
            "defense",
            "handicap.armor",
            "tickmalus.armor",
        ]);
        expect(
            actor.addedModifiers.every((m) => m instanceof Modifier),
            "registry implementations are used"
        ).to.be.true;
        expect(await registeredValue(actor, "defense")).to.equal(2);
        expect(await registeredValue(actor, "handicap.armor")).to.equal(4);
        expect(await registeredValue(actor, "tickmalus.armor")).to.equal(3);
        expect(actor.addModifier.called, "no string modifiers on this armor").to.be.false;
    });

    it("adds nothing when the item has an autoGenerated effect", () => {
        const actor = makeActor(10);
        const item = makeItem("armor", { ...ARMOR_SYSTEM, modifier: "defense +1" }, actor, [{ type: "autoGenerated" }]);

        applyLiveItemModifiers(item);

        expect(actor.addedModifiers).to.deep.equal([]);
        expect(actor.addModifier.called).to.be.false;
    });

    it("still applies the fallback when only a manually created modifier effect exists", async () => {
        const actor = makeActor(10);
        const item = makeItem("armor", ARMOR_SYSTEM, actor, [{ type: "modifier" }]);

        applyLiveItemModifiers(item);

        expect(actor.addedModifiers.map((m) => m.path)).to.have.members([
            "defense",
            "handicap.armor",
            "tickmalus.armor",
        ]);
        expect(await registeredValue(actor, "handicap.armor")).to.equal(4);
    });

    it("suppresses unequipped armor/shield/weapon and inactive spelleffect", () => {
        const actor = makeActor(10);
        const armor = makeItem("armor", { ...ARMOR_SYSTEM, equipped: false, modifier: "defense +1" }, actor);
        const shield = makeItem("shield", { equipped: false, modifier: "defense +1" }, actor);
        const weapon = makeItem(
            "weapon",
            { equipped: false, modifier: "defense +1", features: { hasFeature: () => false } },
            actor
        );
        const spelleffect = makeItem("spelleffect", { active: false, modifier: "focus.reduction 1" }, actor);

        applyLiveItemModifiers(armor);
        applyLiveItemModifiers(shield);
        applyLiveItemModifiers(weapon);
        applyLiveItemModifiers(spelleffect);

        expect(actor.addedModifiers).to.deep.equal([]);
        expect(actor.addModifier.called).to.be.false;
    });

    it("applies equipped armor and active spelleffect with their modifier types", () => {
        const actor = makeActor(10);
        const armor = makeItem(
            "armor",
            {
                equipped: true,
                modifier: "defense +1",
                defenseBonus: 0,
                damageReduction: 0,
                handicap: 0,
                tickMalus: 0,
                minStr: null,
            },
            actor
        );
        const spelleffect = makeItem("spelleffect", { active: true, modifier: "focus.reduction 1" }, actor);

        applyLiveItemModifiers(armor);
        applyLiveItemModifiers(spelleffect);

        expect(actor.addModifier.calledTwice).to.be.true;
        expect(actor.addModifier.firstCall.calledWith(armor, "defense +1", "equipment", 1)).to.be.true;
        expect(actor.addModifier.secondCall.calledWith(spelleffect, "focus.reduction 1", "magic", 1)).to.be.true;
        expect(actor.addedModifiers, "neither item carries property-derived values").to.deep.equal([]);
    });

    it("routes string modifiers of equipment through actor.addModifier", () => {
        const actor = makeActor(10);
        const item = makeItem("equipment", { modifier: "skills.acrobatics +2" }, actor);

        applyLiveItemModifiers(item);

        expect(actor.addModifier.calledOnceWith(item, "skills.acrobatics +2", "equipment", 1)).to.be.true;
        expect(actor.addedModifiers).to.deep.equal([]);
    });

    it("substitutes ${skill} and ${name} on masteries before parsing", () => {
        const actor = makeActor(10);
        const item = makeItem(
            "mastery",
            { skill: "academicMagic", modifier: "${skill} +2, ${name} -1" },
            actor,
            [],
            "Schwerpunkt Feuerschlag"
        );

        applyLiveItemModifiers(item);

        expect(actor.addModifier.calledOnceWith(item, "academicMagic +2, Feuerschlag -1", "innate", 1)).to.be.true;
    });

    it("keeps the plain mastery name when there is no Schwerpunkt prefix", () => {
        const actor = makeActor(10);
        const item = makeItem("mastery", { skill: null, modifier: "${name} +1" }, actor, [], "Rüstungstraining");

        applyLiveItemModifiers(item);

        expect(actor.addModifier.calledOnceWith(item, "Rüstungstraining +1", "innate", 1)).to.be.true;
    });

    it("multiplies live modifiers by the strength item's quantity", () => {
        const actor = makeActor(10);
        const item = makeItem("strength", { modifier: "strength +1", quantity: 3 }, actor);

        applyLiveItemModifiers(item);

        expect(actor.addModifier.calledOnceWith(item, "strength +1", "innate", 3)).to.be.true;
        expect(actor.addedModifiers).to.deep.equal([]);
    });

    it("returns early for an unowned item without touching effects", () => {
        const item = makeItem("armor", { ...ARMOR_SYSTEM, modifier: "defense +1" }, null);
        const guarded = {
            ...item,
            get effects(): never {
                throw new Error("effects accessed");
            },
        } as unknown as SplittermondItem;

        expect(() => applyLiveItemModifiers(guarded)).to.not.throw();
    });
});
