export const ACTION_EFFECT_TYPES = [
    "modifier",
    "spellEffect",
    "spellEnhancedEffect",
    "attackEffect",
    "autoGenerated",
] as const;
export type EffectType = (typeof ACTION_EFFECT_TYPES)[number];
